### ISSUE TITLE
test functions needed

### ISSUE THREAD

**Issue by msarahan** [hyperspy/hyperspy#10]
https://bitbucket.org/francisco/hyperspy/issue/12/test-functions-needed

**Comment by francisco-dlp** [comment]
The situation has improved dramatically since this issue was opened, but we don't have 100% coverage yet.

**Comment by tjof2** [comment]
82% coverage now...! Will this be left open indefinitely?

**Comment by tjof2** [comment]
Codecov.io reports 76% at the moment. Since any PR undergoes a codecov check to ensure test coverage doesn't decrease, it doesn't seem worth keeping this separate issue open. Targeting 100% coverage doesn't go away. Indeed, most developers will be well aware that tests are a key part of the development process, and the dev guide is quite comprehensive on this.
