### ISSUE TITLE
s.decomposition() should raise an error on unsuccessful decomposition

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#1000]
As it currently stands, `s.decomposition()` will happily run on an image without having any effect. It would be nice if it raised an error if it didn't do anything.

**Comment by dnjohnstone** [comment]
Actually I think this is a more substantive bug... I don't seem to be able to make decomposition work at all in the current master

**Comment by thomasaarholt** [comment]
For others - @dnjohnstone's problem turned out to be not having his data as floats. But yeah, it should raise an error.

**Comment by tjof2** [comment]
@thomasaarholt I'm not sure I fully follow what you mean here

**Comment by thomasaarholt** [comment]
Mighty good question that.

**Comment by dnjohnstone** [comment]
I reckon we can probably consider this closed at this point?

**Comment by tjof2** [comment]
For context, trying to gather everything together for #1159, so seeing if this is still an issue

**Comment by dnjohnstone** [comment]
I think there are (or at least were) some instances, e.g. if you pass non-float data to decomposition, where it looks like it's completed and run fine, i.e. no error or warning, but it's actually not done anything.

That was always a bit unusual because type errors normally throw some kind of visible error somewhere and you can figure out what it was but this method just gave nothing. I'm not sure how many other ways there are to get that to happen or if it even still does.

In cases like that, there probably should be some kind of error - although I don't like type checking.

**Comment by tjof2** [comment]
Type-checking is now there: https://github.com/hyperspy/hyperspy/blob/RELEASE_next_minor/hyperspy/learn/mva.py#L194
