### ISSUE TITLE
s.sum(-1) not updating axes

### ISSUE THREAD

**Issue by magnunor** [hyperspy/hyperspy#1005]
When using a sum on the last axis in a 2-D spectrum, the resulting 1-D signal has one nav-axis and no signal axis. This leads to the new signal having an unused spectrum navigation tool.

``` Python
import numpy as np
s = hs.signals.Spectrum(np.arange(10000).reshape(10,1000))
s1 = s.sum(-1)
s1.axes_manager.navigation_axes
(<Unnamed 0th axis, size: 10, index: 6>,)
s1.axes_manager.signal_axes
()
s1.plot()
```

Gives this image (I moved the navigator to make it more visible):
![figure_1](https://cloud.githubusercontent.com/assets/1690979/15426557/230bcfa6-1e87-11e6-94ed-bbc2f1ca9b9e.png)

This happens in both master and 0.8.x branches.

I'm guessing this is not intended, and the return signal should have 1 signal axis.

(This might have been mentioned in some other issue, but I can't remember where...)

**Comment by tjof2** [comment]
Still the same behaviour?

```python
import numpy as np
import hyperspy.api as hs
s = hs.signals.Signal1D(np.arange(1000).reshape(10,100))
s1 = s.sum(axis=-1)
print(s1.axes_manager.navigation_axes)
# (<Unnamed 0th axis, size: 10, index: 0>,)
print(s1.axes_manager.signal_axes)
# ()
s1.plot()
```

**Comment by ericpre** [comment]
I think this is an intended behaviour because by calling `s1.sum(axis-1)`, it is asked to sum over the signal axis, therefore there is no signal axis anymore. @magnunor is expecting to get `s1.sum(axis-1).T`, which is something different from `s1.sum(axis=-1)`, therefore the current behaviour looks fine to me and the `sum` is too generic to perform the transpose automatically in this case.

**Comment by tjof2** [comment]
Good to close then?

**Comment by ericpre** [comment]
Yes, this can be re-opened for more discussion if necessary.
