### ISSUE TITLE
Mayavi in v1.1

### ISSUE THREAD

**Issue by pburdet** [hyperspy/hyperspy#1254]
It looks like mayavi is not in the installation bundle for Windows. Is there a reason for that? I'm planning to use it in the EMC training.

**Comment by francisco-dlp** [comment]
Yes, mayavi is absent from the bundle. Sometime ago we decided not to customise the winpython distribution beyond adding hyperspy and its dependencies.

Unfortunately, there is no way to install it in the workshop computers because the current bundle has already been installed. matplotlib's mplot3d is more limited and slower, but maybe is enough for what you want to show? Otherwise PyQtGraph is also available.

**Comment by vidartf** [comment]
As far as I remember, mayavi does not have an easy-to-include build anywhere for automated inclusion. The Gholke repo explicitly forbids automatically fetching binary wheels, and helps enforce this by switching around the magic numbers in package links. So unless mayavi has started to distribute their own binary wheels, there is not a lot to be done.

**Comment by pburdet** [comment]
Thanks for the answer. mplot3D is too limited and the function "isosurface" of PyQtGraph is crashing (all the other exemples are working appart this one...). I'll do wihout
