### ISSUE TITLE
Online & Robust NMF

### ISSUE THREAD

**Issue by tjof2** [hyperspy/hyperspy#1296]
Building on my recent work with robust PCA (#972 and #1128), I've also got an algorithm together for online, robust NMF (i.e. deals with outliers in a single step) - this is potentially more useful for analysis of EELS/EDS datasets etc. especially if it works in a real-time manner (could be connected to a microscope, in theory...!). 

Also works, with further testing required, with online Poisson noise normalization.

@francisco-dlp and @to266 what's the best way to go about developing this for any integration with HyperSpy, given it belongs with the ORPCA algorithm and less so with the standard NMF routine(s). How does it fit with the lazy signals in #1219, now that @to266 has reworked my ORPCA algorithm?

**Comment by to266** [comment]
The ORPCA rework is only in the PR/branch, so if you choose so, you can just pretend it does not exists :) You are of course also welcome to look at the changes and use the ideas for the next algorithm.

Also, around two weeks ago I email the authors of [this paper](http://arxiv.org/pdf/1608.00075v1.pdf) asking for their code, and the reply was they were currently otherwise busy, but once some free time is available, he'll clean up the matlab code and sent it to me to translate to python.

Is your method/implementation similar? Even if the method in the paper has advantages, I think it's still good to have more than one to choose from.

As for the general developing, the plan is to kind of rewrite the machine learning in hyperspy to be more modular and less restrictive which dataset is used for learning, and which for projecting (and in some cases, using multiple datasets for learning). We should figure out who and when undertakes this, as shoehorning the algorithm into our current structure may not be worth the effort.

**Comment by tjof2** [comment]
Aha, very interesting, in that case it might be worth asking the same author for the code for [this one too](https://arxiv.org/pdf/1604.02634.pdf) - because after I worked out my method, I came across this and realized it was basically the same. My version does the same as the PGD method of Zhao & Tan.

**Comment by tjof2** [comment]
The two papers are different in their aims, but as you say, worthwhile having a few options!

**Comment by tjof2** [comment]
Now implemented, some improvements ongoing in #2035
