### ISSUE TITLE
Gaussians return wrong parameter values?

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#1317]
I get conflicting results on the coefficients returned after fitting a gaussian:
http://nbviewer.jupyter.org/urls/dl.dropbox.com/s/t77kcfc3c2jita2/Testing%20Gaussians.ipynb
This was first reported by Luiz Tizei on email support.

**Comment by to266** [comment]
The signal is binned by default, and it [is important](http://hyperspy.org/hyperspy-doc/dev/user_guide/model.html#curve-fitting). If you set the `binned=False` and fit again, I get these new values:

``` python
In [15]: m.fit()

In [16]: m.print_current_values()
Components  Parameter   Value
Gaussian
        A   20928.6
        centre  8.05248
        sigma   0.0672667
In [20]: s.metadata.Signal.binned = False

In [22]: m.fit()

In [23]: m.print_current_values()
Components  Parameter   Value
Gaussian
        A   419.158
        centre  8.05248
        sigma   0.0672667
```

Which then returns the expected (**both are correct!**) value with your simple estimate:

``` python
In [29]: G.A.value / (G.sigma.value*math.sqrt(2*math.pi))
Out[29]: 2485.9251965619396
```

**Comment by to266** [comment]
Other (irrelevant) things I noticed in the notebook that are strange (though some do what you want..)
- `m.remove(0)` instead of `m.pop(0)`. `pop` returns what it just removed, whereas `remove` does not. You did not want to keep it, so just remove.
- `G.bmin = 7.9` and similar for `bmax`. This does not do anything, since it operates on the component, not parameter. Instead, it should have been `G.centre.bmin = 7.9`.
- `m.print_current_values()` is nice for printing

**Comment by thomasaarholt** [comment]
Thanks. Changing the truth value of `binned` does indeed give a correct answer. I shall continue my quest on figuring out how on earth a gaussian can get a different coefficient depending on the binning of the signal. Cheers for replying to email.

Re code, I appreciate the feedback. Not often enough that someone actually looks over my code.
@magnunor re `m.pop` ;)
bmin/bmax was just a typo.
`m.print_current_values()` is indeed nice.
