### ISSUE TITLE
sc.save("data.rpl") no longer works

### ISSUE THREAD

**Issue by mwalls** [hyperspy/hyperspy#1318]
I can no longer save data in the rpl format. Is this a known bug/development? I need to make some standard Egerton-type maps on de-noised data. AFAIK Hyperspy does not yet provide this? All help gratefully received!
![rpl](https://cloud.githubusercontent.com/assets/1022064/19970026/00ebcd40-a1db-11e6-8fa2-e40c6c076a99.PNG)

**Comment by mwalls** [comment]
OK I have solved my immediate problem by using the hdf5 plugin by Tore Niermann. Thanks very much to Tore! But if we still want to keep the rpl option there would seem to be a bug...

**Comment by thomasaarholt** [comment]
I have no trouble saving to `.rpl` here. The reason your file isn't saving properly is due to the metadata not being set correctly. There is an update that should be available in the next update that ensures the the dm4 file is correctly imported (#1302). For now, what happens if you type
`s.metadata`?

The reason for the error is that the rpl writer is trying to include a acquisition metadata label that is not present (or not set corerctly). For now, if you needed to save it without the plugin, you could type:

``` python
sc.set_signal_type("Signal1D")
sc.save("aa.rpl")
```

**Comment by mwalls** [comment]
Thanks Thomas. Changing it to Signal1D works. For info, the metadata is:
`├── General
│   ├── original_filename = E14030-2-Spim.dm4
│   └── title = Spim-O-1
└── Signal
    ├── binned = True
    └── signal_type = EELS`
