### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#1339]
Is there an existing roadmap or outline for where we want to take Hyperspy? It would be nice to have an idea of what might happen in the future, and it would also let people realise opportunities to collaborate.

**Comment by magnunor** [comment]
I'm guessing the closest is the wishlist: https://github.com/hyperspy/hyperspy/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Wish+list%22
There is also some things in the wiki, but it hasn't been used in quite a while: https://github.com/hyperspy/hyperspy/wiki/HyperSpy-Enhancement-Proposals-%28HSPEPs%29

A roadmap would be nice, but I think due to the "side project" nature of the HyperSpy development it is a bit hard (but not impossible!) to make long term plans. Since most people implement things they need for their own work.

That being said, maybe the "projects" functionality would be useful to organize these things. For example with the holography, or marker implementations. https://github.com/hyperspy/hyperspy/projects

**Comment by francisco-dlp** [comment]
I fully share @magnunor's view. To this day, nobody has ever been employed to develop HyperSpy, therefore development happens when somebody needs a feature which is not yet implemented, hence the lack of a roadmap.

**Comment by thomasaarholt** [comment]
Excellent answers. Happy to close this, though feel free to reopen if people have thoughts on the subject.
