### ISSUE TITLE
Optimized copy warning

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#1360]
Whenever I load any DM signal, I get the message:
`WARNING:hyperspy.signal:<EDSTEMSpectrum, title: EDS Spectrum Image 0eV, dimensions: (150, 279|2048)> data is replaced by its optimized copy`
This can be a bit scary for new users, as was evidenced during our workshop in Oxford last week. Is there a particular need to emphasise that the data has been replaced? As a "normal" user, I don`t even know what the implication is.

The documentation talks about `optimize` in conjunction with `hs.transpose`. Perhaps loading a DM file involves calling this function?

**Comment by francisco-dlp** [comment]
What happens is that the spectrum image is stored in this DM files as a image stack and HyperSpy automatically transposes it in memory in order to optimize the speed of spectrum operations. The warning is automatically generated by `transpose` which is called internally as you guessed. Do you have any suggestion on how to improve the message?

**Comment by thomasaarholt** [comment]
I think we can inform of the DM memory optimisation in the documentation
and include a method of 'no_warning=False' in the transpose function, and
setting it True in the dm load call.

Are there cases where it would catch a user off-guard that the data has
been optimised?

**Comment by francisco-dlp** [comment]
The reason why we warn about the optimisation is that it consists on rearranging the data in memory: this can be slow for big datasets, so I think that we should keep the warning so that the user becomes aware of this potential bottleneck. We should provide the option of not rearranging the data in memory for those cases. We'll have to work on this anyway when implementing the lazy mode of the DM reader for #1219.

**Comment by thomasaarholt** [comment]
Ah, I understand then. So it speeds things up whilst costing memory. That's
fair, I guess. It's just a bit in the way if I load four eels signals at
the same time.

**Comment by to266** [comment]
...is this still relevant? (sorry for closing and reopening)

**Comment by smc204** [comment]
I was talking to a new user today, and I think it is a bit confusing. It looks as if something has gone wrong when nothing has... Perhaps something could be included in the message to explain which cases the warning is relevant/important? It seems to still be relevant, in short...

**Comment by thomasaarholt** [comment]
Could the level of the logging be reduced to "info" instead? Then it would be invisible except for the users who want it. The logging level can be set with `hs.preferences.gui()`.

**Comment by francisco-dlp** [comment]
It sounds good to me. In that case, maybe we could also add a message informing that the data is just a view of the original one when a copy is not performed?
