### ISSUE TITLE
Swap dimension functionality

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#1387]
What do people think of a shortcut method for swapping the dimension?
Just `s.swap()` or `s.switch()`, similar to `s.T`.

`s.T` rotates the image by 90 degrees when used on a map/image. I know about s.swap_axes(), and s.as_signal2D(), but it when showing Hyperspy to others it can be a bit hard to explain.

For EDS and EELS data, the transposed view is the default way of viewing signals in DigitalMicrograph, and it might be nice for new users of hs to have the option.

**Comment by francisco-dlp** [comment]
`s.T` should do what you want...but it doesn't...which is a bug!! I don't know how this serious bug could be introduced without breaking the tests.

**Comment by thomasaarholt** [comment]
WHAT :D 
Well, that explains that. I thought it was intended behaviour - noone seemed to raise an eyebrow when I've mentioned it on the chat.

**Comment by to266** [comment]
Actually I'm not sure if it's a bug. When writing the `transpose`, one of the goals was to reorder the numpy axes as little as possible. While `s.T` obviously does not preserve the `C_CONTIGUOUS` flag, it rather becomes `F_CONTIGUOUS`, as expected. To get something that plots the navigator axes in the same x-y fashion it requires swapping data axes:
```python
In [3]: s = hs.signals.Signal2D(np.empty((4,5,6)))

In [4]: s
Out[4]: <Signal2D, title: , dimensions: (4|6, 5)>

In [5]: s.data.flags
Out[5]: 
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [6]: s.T
Out[6]: <Signal1D, title: , dimensions: (5, 6|4)>

In [7]: s.T.data.shape
Out[7]: (6, 5, 4)

In [8]: s.T.data.flags
Out[8]: 
  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [9]: s.transpose(navigation_axes=(1,2))
Out[9]: <Signal1D, title: , dimensions: (6, 5|4)>

In [10]: s.transpose(navigation_axes=(1,2)).data.shape
Out[10]: (5, 6, 4)

In [11]: s.transpose(navigation_axes=(1,2)).data.flags
Out[11]: 
  C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False
```

**Comment by francisco-dlp** [comment]
The reason why I think that this is a bug is that it does not behave as documented, from the docstring:

```python
>>> s = hs.signals.BaseSignal(np.random.rand(1,2,3,4,5,6,7,8,9))
>>> s
<BaseSignal, title: , dimensions: (|9, 8, 7, 6, 5, 4, 3, 2, 1)>

>>> s.transpose() # swap signal and navigation spaces
<BaseSignal, title: , dimensions: (9, 8, 7, 6, 5, 4, 3, 2, 1|)>

```
I think that this the most useful and intuitive behavior: why should transpose reverse the order of the axes? In @thomasaarholt example, this causes an unexpected 90 degrees rotation. Beside, being C contiguous is useful to speed up navigation axes iteration with e.g. `map`, but F contiguous data is not useful for this.

**Comment by to266** [comment]
I would not trust the docstring, as I changed it a number of times while trying to figure out what's the most sensible behaviour...

Anyway I'll PR a fix for this with the docstring as the correct behaviour, as it's a trivial change. We'll see what breaks.

**Comment by francisco-dlp** [comment]
> I would not trust the docstring

:0

**Comment by thomasaarholt** [comment]
**shots fired**

I'd understood it as being a feature. If the signal has shape:
```python
>>> s = hs.signals.BaseSignal(np.random.rand(1,2,3,4,5,6,7,8,9)).as_signal2D((-2,-1))
<Signal2D, title: , dimensions: (9, 8, 7, 6, 5, 4, 3|2, 1)>
```
Then things get funny because the numpy array shape is:
```python
>>> s.data.shape
(3, 4, 5, 6, 7, 8, 9, 1, 2)
```
My mind is already jelly at this stage, but I don't understand why the two shapes are so different. *Why* is the dimension order reversed in the first place?

**Comment by to266** [comment]
PR'ed a fix, was actually a bug, nice catch.

**Comment by francisco-dlp** [comment]
Thanks! You've spotted three more bugs when you mentioned rightly that the docstrings are not trustful #1392, #1393 and #1394.

**Comment by to266** [comment]
@thomasaarholt a couple of things combined:
 - Depending how the array is arranged, some axes are faster to iterate than others. Consider an example of a book as the dataset in question. It is trivially simple to look at letters in a line, and then lines down the page, and finally pages in the whole book.  However if your words are written vertically, it's slightly inconvenient to read top-down (the lines are still horizontal, it's just the meaning that's vertical!). It's just awful if every letter is on a different page, and for every word you have to turn 5-6 pages. Exactly the same idea applies here - in order to iterate through the data (most often for plotting, but applies for any other operation too), you want to keep it ordered for "fast access".
 - In python (more explicitly `numpy`) the "fast axes order" is the C-order, corresponding to the `C_CONTIGUOUS` flag you may have noticed before. This means that the __last__ axis of a numpy array is fastest to iterate over (i.e. the lines in the book). There are alternatives in other languages, namely the F (for Fortran)-order, where it's the reverse - the first axis of an array is the fastest to iterate over. Usually in all implementations iterating over some axis in the middle is slow, as you have to "pick the same line from all pages", or something similar.
 - Most datasets are recorded in the C-order. Taking EDS / EELS map as an example, the dataset has three dimensions/axes - the fast, and slow real-space, and the energy channels. If you think how the microscope works, it's obvious that the energy axis is the fastest, then the x, and finally the y is the slow axis. So to record it in C-order, you store it in an array (y, x, E). If this was a SPED dataset, you would record this in (y_real, x_real, y_recip, x_recip) with real and reciprocal spaces respectively.
 - In HyperSpy we want to order these things for humans. __Which means x axis goes before y__. This is also why the `transpose` was quite mind-numbing to write and get right.. So for EDS/EELS we go from (y, x, E) to `<x, y | E>` in HyperSpy, and for SPED from (y2, x2, y1, x1) to `<x2, y2 | x1, y1>`.  So actually the axes that are "close" in this last example are not y2 and x1, but x2 and y1, even though in HyperSpy these look to be on the opposite ends. 
 - If you extend this to arbitrary dimensions you'll realise that we essentially reverse the numpy axes, chop it into two chunks (signal and navigation), and then swap those chunks, at least when printing. (@francisco-dlp will hopefully explain __why__ we actually print the signal axes last, since having written this I now realised I have no idea, and it would make things so much simpler....) Anyway, this happens:
```
(a1, a2, a3, a4, a5, a6) # original (numpy)
(a6, a5, a4, a3, a2, a1) # reverse
(a6, a5) (a4, a3, a2, a1) # chop (What we'd have if we did not swap the representation... I want this!)
(a4, a3, a2, a1) (a6, a5) # swap (HyperSpy)
```
 - When you call `as_signal*D`, it really just calls `transpose` with `optimize=True`. The `optimize` means that if you happen to request to read the book in the way where one word with 5 letters requires to look at 5 different pages, then HyperSpy (numpy) __rewrites__ the book so that they are actually in lines now.  This obviously creates a new book (copy of data, more memory, etc.), but it's fast to read!

**Comment by thomasaarholt** [comment]
Excellent analogy and phenomenal response. Really appreciate, thank you!

**Comment by francisco-dlp** [comment]
So good that it's worth considering adding it to the User Guide!

**Comment by francisco-dlp** [comment]
#1391
