### ISSUE TITLE
Model p0 master array?

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#1460]
Are the parameter values set on a pixel by pixel basis, or is there some master array that p0 gets its data from?
The reason I ask, is that looping through the arrays takes fifty times longer than actually doing the linear fitting for the whole spectrum image (2000 pixels).

If I could somehow bypass the `self._fetch_values_from_p0()` (which I assume is necessary for updating the fit in each pixel) and feed the whole array I have of new p0 values to some "master array" for the parameter values, then that would speed things up significantly.

**Comment by francisco-dlp** [comment]
I would suggest to first implement it in the straightforward way i.e. iterating over the navigation dimensions and later (maybe in a another PR?) add the possibility to fit the whole dataset at once.

To reply your question, yes the values are set on a pixel by pixel basis. To achieve what you want you may need to create a similar method that instead of updating ``Parameter.value`` updates ``Parameter.map["values"]``.

**Comment by to266** [comment]
I guess it might be problematic to disable certain components in a subset of pixels if fitting all in one go.

Also, even though we currently don't do this, in principle the `parameter.map` array could be a memmap - hence not requiring memory. Fitting everything in one go would require reading it into memory, limiting this. Just something to keep in mind for future

**Comment by thomasaarholt** [comment]
@francisco-dlp That's exactly what I was looking for! That's way easier!

In any case, I'm now working on PRing the standard linear fitting first.

**Comment by francisco-dlp** [comment]
What about closing this then?

**Comment by thomasaarholt** [comment]
Sorry :)
