### ISSUE TITLE
Warn when plotting signal that contains markers

### ISSUE THREAD

**Issue by francisco-dlp** [hyperspy/hyperspy#1511]
A signal can contain permanent markers but they are not plotted by default. Although it is possible to know if it contains markers by checking the metadata, wouldn't it be useful to add a warning to the logger when plotting a signal that contains markers when ``plot_markers`` is ``False``?

**Comment by magnunor** [comment]
I don't think this is a good idea, since markers will be added to signals automatically (for example https://github.com/hyperspy/hyperspy/pull/1491). This means that at some point, when more of the file loaders also adds markers, pretty much every `s.plot(plot_markers=False)` will produce a warning.

Semi-related: we could make `plot_markers=True` the default

**Comment by ericpre** [comment]
It looks like users don't like to see warning... maybe it is best to avoid it, if not very important.
+1 on making plot_markers=True, the default.
This default could be set in the preferences. It could also be signal dependant.

**Comment by thomasaarholt** [comment]
+1 for the plot_markers=True as well. @magnunor's argument about constant warnings is true.

**Comment by sem-geologist** [comment]
+1 for `plot_marker=True`; or it should go to `logger.info`, not `warnning`. Bcf v2 is going to have marker too (only one rectangle only on overview image,but it would be nice if it would be plotted automatically)

**Comment by ericpre** [comment]
Fixed by #1564.
