### ISSUE TITLE
Import EELS-data from a text-file

### ISSUE THREAD

**Issue by WolfgangKoe** [hyperspy/hyperspy#1683]
Hello,

since I didn't find such an issue, it's either too trivial or noone produces EELS-data in .txt-files. I just startet to analyse my EELS-data with hyperspy, but I don't get it loaded. Well, I know it is possible, but my first tries didn't work so far. Maybe someone can tell me, at which point something goes wrong and how to fix it.

I'm using hyperspy on Linux in an anaconda-environment. 

`Python 3.6.1 |Anaconda 4.4.0 (64-bit)| (default, May 11 2017, 13:09:58) `

I have EELS-data in a .txt-file and want to load it in hyperspy. The .txt-file is written like this

`0.000 4.34235`
`0.500 4.45677`
`1.000 4.4356`
`1.500 4.62745`
`...`

while the first column is the energy-loss and the second the counts on my camera. If  understand the hyperspy documentation right, in the end hyperspy should in interpret the first column as navigation and the second column as signal. But I'm not sure at this point. 

However, I can load this file as a numpy array in hyperspy using:

`file = np.loadtxt('EELS_data.txt')`

what gives me:
`array([[0.000      ,     4.34235], [0.50     ,     0 4.45677],[1.000     ,      4.4356],[1.500     ,      4.62745], ....]])`

Than I said hyperspy to interpret this data with:

`s = hs.signals.Signal1D(file)`

The Plotting result is then the following:

![figure__signal](https://user-images.githubusercontent.com/29704832/27829462-07e04a3a-60c2-11e7-8708-bb2a0a3c93dc.png)

What is of course unreasonable. I guess, that something is wrong when I'm loading the data with numpy, but I don't know, if that is the case. 

Thanks for your help.

**Comment by thomasaarholt** [comment]
You can access the energy loss and counts separately using array slicing, the standard way of "cutting" matrices and arrays in numpy (and hyperspy).

In your case, after loading in `file` in the way you did it, slice it as follows:
```python
energy = file[:, 0] 
counts = file[:, 1]
```
The colon refers to "all" entries, so in the first case we ask for an array of all entries in `file`, but only the first value in each entry. Note that in numpy counting starts with 0.

Now that you have your counts, you should load it into a hyperspy signal:
`s = hs.signals.EELSSpectrum(counts)`
In order to calibrate it, you must set the offset (here it is zero), scale (0.5 eV per channel in your case) and the units ("eV").

Since you have a single spectrum, the axes_manager only has one axis - the energy axis. It is normally the last axis, but since we only have one it is also the first:

```python
s.axes_manager[0].offset= 0
s.axes_manager[0].scale = 0.5
s.axes_manager[0].units= "eV"
```
Then plot it using `s.plot()`

**Comment by WolfgangKoe** [comment]
Thanks, this could work, I will give it a try tomorrow.

**Comment by WolfgangKoe** [comment]
So I tried this way and it worked fine. It was really a trivial problem in the end ;-). Just a few cosmetics left, but these won't be a problem.

Thanks
