### ISSUE TITLE
Matplotlib qt and traits GUi error

### ISSUE THREAD

**Issue by jdsugar** [hyperspy/hyperspy#1784]
I have followed the installation instructions as best I can, and I am continuing to have issues with matplotlib qt and traitsui on my Mac.

(1) First, if I start up hyperspy following the instructions it looks like the following:

In [1]: %matplotlib qt

In [2]: import hyperspy.api as hs
WARNING:hyperspy.api:The traitsui GUI elements are not available, probably because the hyperspy_gui_traitui package is not installed.

I can not figure out how to get the traitsui installed. I see it in my site packages, and I use pip and conda and it just doesn't work.

(2) Even if I ignore the traitsui error, I have a problem when I try to plot. I get this error that says "QWidget::repaint: Recursive repaint detected" and then things eventually lock up and nothing happens. 

(3) if instead of the matplotlib qt, I just say %matplotlib, then I use the MacOSX backend, and plot seems to work OK, but I still can't get the traitsui gui to work.

Does anyone know what is going on with my installation? Can anyone provide some help with this?

Thanks,
Josh

**Comment by ericpre** [comment]
You may have (at least two) different issues here... just to make sure, what are your matplotlib and pyqt versions?

- The recursive error is most likely due to matplotlib 2.1, downgrading to 2.0 should fix it. Alternatively, #1760 should fix it but you will need to install this specific branch.
- you should be able to run hyperspy in the notebook with pyqt=5 and the ipywidgets -requires hyperspy_gui_ipywidgets. Alternatively, you could possibly downgrade to pyqt=4 from the conda-forge repository, although I am not sure how wlell it is working at the moment and you may need to uninstall "anaconda-navigator" or something similar to resolve the dependencies conflict.

The easiest for you is possibly to use hyperspy in the notebook with the macosx backend and ipywidgets for the ui.

**Comment by jdsugar** [comment]
I am new to some of this. Would you mind telling me how to downgrade matplotlib? Also, I have already uninstalled anaconda-navigator as the installation instructions say to in order to install the _gui_traitsui. I also have tried to downgrade pyqt, but again I would say that I am not sure I was using the correct commands, so I might have screwed that up. Any specific commands you can provide would be extremely helpful. Thanks again...

**Comment by jdsugar** [comment]
Oh I forgot...
pyqt5 5.9.2
matplotlib (2.1.0)

**Comment by ericpre** [comment]
To downgrade pyqt:
```
conda install -c conda-forge pyqt=4
```

to downgrade matplotlib:
```
conda install -c conda-forge matplotlib=x
```
with x = 1.5 or x = 2.0 depending on the pyqt version currently installed and therefore the dependency conflict.

**Comment by jdsugar** [comment]
I tried the condo install for pyqt, it said that it was already installed. I couldn't figure out what to do with pyqt.

For matplotlib, I tried:
pip install --upgrade matplotlib==2.0

This seemed to help. Now I can load %matplotlib qt, and it seems to work. There is still some buggy stuff when I try to change the size of a box with + and - and sometimes I get a spinning color ball until I click in all the different windows. Sometimes it goes away, sometimes my terminal locks up and I can't type in there anymore. If I use plt.close('all'), this helps sometimes too. So, I guess there is some sort of conflict still, but I think it is working enough so that I can learn hyper spy for now.

I still can't get the traitsui GUI elements to load, but that is maybe not so important. 

Thanks for the help.

**Comment by ericpre** [comment]
If you have pyqt5 installed, `conda install -c conda-forge pyqt=4` should downgrade pyqt, if this is not the case, then there is something broken somewhere.
The UI with hyperspy_gui_traitsui is not working most likely because you have pyqt=5. You should still be able to use the UI with hyperspy_gui_ipywidgets.

**Comment by jdsugar** [comment]
When I tried to downgrade to pyqt4 I got this:
# All requested packages already installed.
# packages in environment at /Users/jdsugar/anaconda3:
#
pyqt                      4.11.4                   py36_2    conda-forge

Is there a way to check that the hyper spy_gui_ipywidgets is working. I see that folder exists in my python installation, but when I try for example, hs.preferences.gui() I just get text with no actual gui. Is there something I have to do to activate or use ipywidgets?

**Comment by ericpre** [comment]
The ipywidgets are working in the jupyter notebook and it looks like [that](https://github.com/hyperspy/hyperspy_gui_ipywidgets#usage). Then you should be able to select the ipywidgets_gui in the preferences if this is not already the case.

**Comment by ericpre** [comment]
@jdsugar, have you managed to sort out your issue? What the status of this?

**Comment by jdsugar** [comment]
I still get the error when I load the HyperSpy.api, but the preferences GUI pane does come up when I call it and it shows that the GUI checkbox is checked. So I don’t understand why I get the error, but the GUI does seem to work in the Jupyter notebook. In iphthon, the GUI does not work, but I gave up on that.

**Comment by ericpre** [comment]
Closing this because the issue has been solved since traits/pyface support qt5 and installing HyperSpy >= 1.3.1 using Anaconda works fine on mac -see the [installation instruction](http://hyperspy.readthedocs.io/en/stable/user_guide/install.html#quick-instructions-to-install-hyperspy-using-anaconda-linux-macos-windows) from the user guide.
