### ISSUE TITLE
IMC19 Abstract authors

### ISSUE THREAD

**Issue by francisco-dlp** [hyperspy/hyperspy#1856]
As discussed in gitter, I will soon submit an invited abstract to the [IMC19](http://imc19.com). In previous similar situations we've often taken the approach of i) adding every contributor as author (e.g. #1468) but sometimes we've gone for ii) adding none when it was considered more appropriate (e.g. #928). I would go for the first option again, except that, upon reflection:

1. more than 30 people have contributed to HyperSpy to this day. This is already too many for a  conference abstract in our domain, and, hopefully, the situation will only worsen with time.
2. A fraction of those contributors contribute no more. Those contributors have been already acknowledged in past scientific outputs, and of course will carry on being acknowledged in the zenodo DOI but, should all be credited in perpetuity in all scientific output from the project?
3. Another fraction of those contributors have made minor contributions compared to the rest. Those contributions are very welcome and acknowledged by authorship in our zenodo DOI, but should they lead to authorship in academic output?

So, I think that the time is ripe to set a rule to generate the list of authors for this abstract and future scientific outputs.

I propose the following draft (obviously all of it is open for discussion)

```python
authors = []
for contributors in hyperspy.contributors:
    if (made_a_significant_contribution(contributor) and
           last_contribution_time < x_amount_of_time):
        authors.append(contributor)
```
    
We could define a ``significant contribution`` as a significant number of non-trivial (i.e. typos fixing) contributions of to code, documentation and review.

The ``x amount of time`` could be ``max(time_since_last_scientific_output, y)``, where  ``y`` should be set to a time span that encourages frequent contributions while allowing for reasonable breaks (as nobody's main activity here is software development). Does e.g. ``y=1 year`` sound reasonable?

In addition, in a private exchange, @ericpre suggests the concept of "Emeritus contributor" i.e. a contributor whose contribution is considered important enough to always deserve mention in the scientific output of the project. In this case the rule would be something like:

```python
authors = []
for contributors in hyperspy.contributors:
    if (made_a_significant_contribution(contributor) and
           (last_contribution_time < x_amount_of_time) or is_emeritus(contributor))):
        authors.append(contributor)
```

So, what do you all think? To make it easier to reply to this long post you can focus on the following questions:

* Do you agree with setting a rule similar to the above?
  * If yes:
    * What should be the value of ``y`` and why?
    * Do you agree with having emeritus contributors in the sense stated above?
      * If yes, who would you like to nominate for this occasion?
  * if not, why?

As I need to submit as soon as possible (sorry for the late notice), please do reply as soon as you can as if we cannot reach consensus soon enough I may go for option ii) (half-joking, but just half ;) )

**Comment by magnunor** [comment]
Hmmmm, I'm not really certain what the best solution is, but we obviously need some kind of way to make the author list short enough to fit conference standards.

I'm guessing the problem then becomes how to define `significant_contribution`, since having to make a lot of judgement calls can potentially be non-trivial.

**Comment by francisco-dlp** [comment]
Initially I also thought that defining "significant contribution" was going to be the hardest challenge. However, probably in practice it is easier than it seems because most minor contributors only contribute once, so  only the most recent minor contributors would pass the second filter. From those (a small number), it is usually easy to check / remember / judge if the contribution is significant or not because the contributions are recent. Of course mistakes in judgement can and will be made due to lack of statistics, but then, if somebody's contribution was wrongly considered (not) significant enough for a given scientific output, if the contributor stops/continues contributing he(*) won't/will be given authorship in the next scientific output.

The objective is, as always, promoting collaborative development. No system will ever be fully fair and error proof. The question (for all) is: do you think that awarding authorship in the way proposed above provides a little extra motivation for scientists to help forge projects such as this one?

(*) obviously this is a neutral "he" meaning she/he, here and elsewhere

**Comment by dnjohnstone** [comment]
For an IMC abstract I personally think you should just put it in as a single author (yourself since you're the one that's been invited) and move on. This is presumably not what people are going to cite if they cite hyperspy in any case. Perhaps you could title it about python based data analysis for EM or something to remove the direct link to HyperSpy in the abstract?

I think it's pretty clear to everyone that your contribution is significantly different to everyone else both in respect to length of time, scope, vision and quantity. 

Differentiating between other people is a bit less clear to me... To me doing something like adding something like SAMFire (which is general and likely to be a core feature or the basis of one for a very long time) is very different to doing something like adding an io_plugin (which is application specific and conceivably becomes irrelevant every couple of years) or EDX tools (which are application specific) - but in terms of time, effort, lines of code, commits (i.e. the things hyperspy has traditionally recognized) these are likely similar. 

You might also argue that academic supervisors who have funded peoples work and suggested or discussed functionalities that have then 'simply' been coded by someone else have made 'significant contributions' but that's not the way recognition has traditionally worked for hyperspy. As soon as you start making a judgement about who made a 'significant contribution' though I think you have to also answer these questions.

In the end - this should be improved significantly by splitting hyperspy! The number of contributors to hyperspy-core will be lower and there can conceivably be citable works for 'independent' extension packages when they add sufficient functionality to be specifically significant as has happened with Atomap for example.

**Comment by francisco-dlp** [comment]
@dnjohnstone, thanks for your input, you raise very important points. I disagree with most of it, but I think that that's because we are trying to solve different problems. The aim of the rule that I propose above is not to import the authorship conventions of academia to HyperSpy (i.e. to play by the same rules or to be fair by those standards) but to provide an extra incentive for scientist to contribute their code by giving them credit where (currently) matters in academia. The reason why we have to do this is because still today things like HyperSpy are not considered research output by most academic institutions and funding bodies and, therefore, contributions to such projects are easily disregarded in terms of career progression in academia. I'll reply to your comments one by one below.

> For an IMC abstract I personally think you should just put it in as a single author (yourself since you're the one that's been invited) and move on.

I wouldn't have been invited to talk about HyperSpy if HyperSpy wasn't what it is today, and it wouldn't be what it is without the work that the many contributors have put on it.

> This is presumably not what people are going to cite if they cite hyperspy in any case

That's a good point. We should maybe start advertising indexed abstract such as this one in the Citing section of the website as an alternative (there are journal that don't accept citing a software DOI) or complement to the zenodo DOI.

> To me doing something like adding something like SAMFire (which is general and likely to be a core feature or the basis of one for a very long time) is very different to doing something like adding an io_plugin (which is application specific and conceivably becomes irrelevant every couple of years) or EDX tools (which are application specific) - but in terms of time, effort, lines of code, commits (i.e. the things hyperspy has traditionally recognized) these are likely similar.

That's true, and that's why there will be a SAMFire paper in a scientific publication but there won't be any paper about the ripple reading plugin. The rule above is trying to give a extra incentive to the person coming up with the next SAMFire-like feature to contribute it to HyperSpy. That's the very reason why HyperSpy exists: there are too many papers out there that describe wonderful computational methods but don't come with the code in an usable form and, therefore, are useless for the potential users who don't have the knowledge or the time to code them. The idea is to encourage people to go the extra step and contribute their work somewhere where others can easily use it. In our community, before HyperSpy existed, there wasn't a default place to contribute code other than the DM script repository. 

> You might also argue that academic supervisors who have funded peoples work and suggested or discussed functionalities that have then 'simply' been coded by someone else have made 'significant contributions' but that's not the way recognition has traditionally worked for hyperspy.

Again, the idea is to give academic credit to the people who 'simply' code and contribute their code to HyperSpy because the perception that coding is 'simple' or, in other words, not valuable, is widespread in academia. However, I think that we all agree in that i) coding can be as hard as other scientific tasks considered hard (the proof is the many ways in which scientific codes can be wrong) ii) even if it was simple, making scientific code available boosts scientific progress, so it must be encouraged (if you want proof for HyperSpy's case, look at the number of papers citing it).

An unfortunate typical scenario in today's academia is that people who 'simply' code don't get credit in scientific papers, hence they don't manage to make progress in their scientific carer. The rule above should help HyperSpy contributors with this, even if just a tiny bit.

The case that you suggest, an academic supervisor who funds people's work and suggests and discuss functionalities that are 'simply' coded by a subordinate is an interesting one. I would say that most academic supervisors are not programming managers. If they contribute ideas, these are mainly scientific ideas and those ideas do get credited in scientific publications. If an academic supervisor ever acts as a programming manager for HyperSpy (i.e. somebody guiding and helping others in programming tasks, without contributing himself), then I agree that we should also give credit to this person. Regarding funding, simply funding a scientific work (without contributing to it) does not (or should not) make you author of a scientific paper—why should funding somebody who contributes to HyperSpy makes you author a HyperSpy's scientific output?

**Comment by dnjohnstone** [comment]
Perhaps you could answer the following:

1. What is a significant contribution? You imply it's easy to decide - my point of comparing qualities of different types of contribution was to suggest it's not obvious to decide - is it measured in lines, commits, originality, generality? If this threshold is high then this will only be a deterrent to contributing code to the project - not an encouragement.

2. When is a set of significant contributions so significant that they are forever significant. (i.e. what makes someone emeritus). The answer now may not be the obvious answer in 10 years - will you then revoke emeritus authorship?

3. What happens when the list obtained by the criteria you set above is still too long for an abstract submission that has a limit on it e.g. I recently submitted to a conference which was max. 9? Have you applied whatever the rules for 1/2 are and checked this will even be ok for IMC?

Regarding indirect coding contributions: first - there was an important AND in my comment, I don't think only funding should merit authorship, but pragmatically it is essential for the work to happen and when combined with intellectual input I'm fine with that qualifying as significant.

I don't think I'm suggesting importing typical standards from other parts of academia either - it's just that when you impose a judgment on significance the same issues of judgment arise. Someone judging a coding contribution to be less significant than some other contribution to a paper can hurt, but I think it's often not malicious it's just hard to draw comparisons. To turn it around - you're now judging that essential contributions for the coding work to happen (funds and ideas are essential) are less significant (or more specifically, not significant at all since it is not recognised) than the coding itself. Whilst that might feel like some kind of earned right by coders being overlooked in other work it's just having a different value structure by which to make your judgment. In other scientific coding projects E.g. pymatgen or diffpy papers often include people in a manner more like this.

**Comment by ericpre** [comment]
This is great that this discussion is taking place and it seems that a few interesting things are going to come out of this!
I think that the general approach is very good and I am convinced that this kind of acknowledgement is important to help building a community.

General comments:
- defining the objective and the actual implementation (ways to achieve it) are two different things which need to be considered separately. I guess this is what @francisco-dlp meant in his first post but I just wanted to emphasise on this.
- obviously after this first attempt this will get improved over time and this should not stop us starting using this approach.
- we should investigated how are doing other scientific projects but most of the time, there is a strong lead from one or two labs, which is clearly not the case of hyperspy.
- consider other contributions (i. e. other than code) which are measurable, such as discussion on issue tracker, PR review (not the most enjoyable thing...), mailing list, etc?

A few details:
- we could design a model with adjustable parameters, which would fit to different situations, for example a limited number of authors on a communication. We could also parse the contribution statistics of specific part of the hyperspy code (io plugin for a communication on metadata, file format, etc or lazy stuff for a communication on big data, etc.)
- maybe the _emeritus_ status could be only for a few years but extendable. Including emeritus or not could also be one of the adjustable parameters?

And a bad joke (slightly off topic) to finish this message: I am regularly impressed by my academic colleagues in most part of the world how good/inventive they can be when it is to care about them self, so this discussion should not be a big deal for them!! :smile:

**Comment by magnunor** [comment]
I feel that including people who has contributed to the code is the right way to go, and not only include the author of the talk. In my opinion the easiest way would be to include people sorted by number of commits, to some cut-off, depending on how many authors is appropriate to have on an abstract/talk.

Of course, in the talk itself, all people should be included in on a slide, to acknowledge all the contributions. At some point, this might not work due to it being too many contributors, but then we can simply set some kind of cut-off, similar to the author list.

**Comment by francisco-dlp** [comment]
Excellent news: there was no limit to the number of authors so everybody is in except for contributors who have only contributed typo corrections and the ones who don't have a real name and affiliation in their profile (as both were required in the submission form).

As @dnjohnstone mentioned above, I should have checked if there was a limit to the number of authors, but as there were no guidelines other than the submission form, I couldn't know for sure if there was a limit until I have performed the experiment of actually submitting an abstract with ~30 authors.

Thanks to all who have participated in this discussion. There is no clear conclusion out of it, which is unsurprising as we're trying to square the circle. I am very glad that this time it was possible to have everybody in.

**Comment by thomasaarholt** [comment]
Too late to the party for comments before submission, but I'm glad that you were able to add extra authors. I think it means much for us to be included, perhaps particularly for phds and new postdocs who are looking to add more to their list of publications.

**Comment by k8macarthur** [comment]
I guess this can be closed now?
