### ISSUE TITLE
EELS example dataset

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#1985]
For testing purposes it would be nice to have an example EELS dataset to rely on. I know we can access eelsdb, but that can introduce errors should it be down or the api change.

Does anyone have a fun pair of lowloss and coreloss spectra that they can contribute with? Otherwise I'll find one of my own.

**Comment by magnunor** [comment]
You could try https://github.com/hyperspy/hyperspy/blob/RELEASE_next_minor/hyperspy/datasets/artificial_data.py.

Including binary data in git repositories isn't ideal, since they don't work well with the version control, and changing anything in them can quickly lead to the size of the repository growing.

**Comment by thomasaarholt** [comment]
Very good suggestion. I wasn't aware of the artificial data!
