### ISSUE TITLE
Loading Qt backend in Jupyter Notebook with Hyperspy 1.4 crashed my kernel

### ISSUE THREAD

**Issue by Sputn1k7** [hyperspy/hyperspy#2051]
I recently upgraded my Hyperspy package to 1.4, and upon attempting to execute an existing notebook, my Jupyter kernel crashes on using the %matplotlib qt5 jupyter magic command.

Has anyone else run into this problem?

**Comment by magnunor** [comment]
I had the same problem, try to use `%matplotlib qt` instead

**Comment by ericpre** [comment]
As usual with this, they may be several things convolved. 

@Sputn1k7: it is very likely that updating hyperspy to 1.4 would have updated matplotlib to the last version. Make sure you are using a newly started kernel try to set the matplotlib backend.
If you are using the qt backend, it should be better to `%matplotlib qt` instead of `%matplotlib qt5`, as it is recommended in the user guide. There was a change related to this in one of the matplotlib release in the last year, which is why you see it now.

**Comment by Sputn1k7** [comment]
Trying %matplotlib qt also crashes my kernel. should I try uninstalling/re-installing hyperspy? I just used conda update hyperspy -c conda-forge to go from 1.3 to 1.4.

**Comment by francisco-dlp** [comment]
The issue doesn't seem to be in HyperSpy itself, so uninstalling it shouldn't help. Probably the particular mixtures of other package versions in your installation is the issue. You could try updating all the packages, possibly after removing the ``conda-forge`` channel from your list if it's in there.

```bash
conda update --all
```

**Comment by Sputn1k7** [comment]
looks like that did it, thanks @francisco-dlp !
