### ISSUE TITLE
Syntax error on import hyperspy.api on Python 3.4.3

### ISSUE THREAD

**Issue by Noiredd** [hyperspy/hyperspy#2083]
I installed HyperSpy with pip (`sudo python3 -m pip install hyperspy`) in my Python 3.4.3 environment. I'm not using pyenv or anything like that, the only out-of-the-ordinary thing is that I also have a 2.7.6 version installed.

The problem occurs as soon as I import HS. Even the following piece of code reproduces the error:  
`python3 -c "import hyperspy.api"`  
returning a `SyntaxError`. Here's the traceback:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/hyperspy/api.py", line 1, in <module>
    from hyperspy.api_nogui import *
  File "/usr/local/lib/python3.4/dist-packages/hyperspy/api_nogui.py", line 75, in <module>
    from hyperspy import signals
  File "/usr/local/lib/python3.4/dist-packages/hyperspy/signals.py", line 42, in <module>
    from hyperspy.signal import BaseSignal
  File "/usr/local/lib/python3.4/dist-packages/hyperspy/signal.py", line 35, in <module>
    from hyperspy.axes import AxesManager
  File "/usr/local/lib/python3.4/dist-packages/hyperspy/axes.py", line 1218
    **dict.fromkeys(['left', dim0_decrease, '4'], (0, -1)),
     ^
SyntaxError: invalid syntax
```

Does that mean that Python 3.4 simply will not let me run HS?

**Comment by ericpre** [comment]
It means that python 3.4 is not supported, because this syntax have been introduced in python 3.5, see https://docs.python.org/3/whatsnew/3.5.html#whatsnew-pep-448.

They may be other things not working in hyperspy for python 3.4 and also possible dependencies not supporting python 3.4.
Even if we were to fix syntax invalid for python 3.4, it will no be straightforward to maintain it properly (the main concern being testing and potential dependencies issues), so this is something which needs to be discussed.

Do you have any specific reason not to use a more recent version of python? Python 3.7 is up to speed now and there are significant benefit to use more recent python version.

**Comment by Noiredd** [comment]
Okay, I understand it. This exact error does not occur in 3.5 (or later, I believe).

**Comment by thomasaarholt** [comment]
Aw man, my bad. I can supply a fix in the future if someone has a need for hyperspy in Python 3.4.
