### ISSUE TITLE
The download link is broken

### ISSUE THREAD

**Issue by IvoMerchiers** [hyperspy/hyperspy#2161]
The first link in http://hyperspy.org/hyperspy-doc/v1.1/dev_guide.html#start-using-hyperspy-and-understand-it should relate to the a download page.
Apart from google flagging it as being in-secure, it leads to a 404 page.

**Comment by magnunor** [comment]
Thanks for the bug report!

The link there is from an old version of HyperSpy's user guide (1.1), but the same issue is present in the most recent version: http://hyperspy.org/hyperspy-doc/current/dev_guide.html#start-using-hyperspy-and-understand-it

The reason is http://hyperspy.org/download.html has been removed, and replaced with http://hyperspy.org/hyperspy-doc/current/user_guide/install.html

**Comment by ericpre** [comment]
Fixed in #2199.
