### ISSUE TITLE
Standard error in PowerLaw fit in Remove Background function

### ISSUE THREAD

**Issue by danwell32** [hyperspy/hyperspy#2207]
I am interested to know the standard errors associated in the Power Law fitting used in the remove background function for an EELS signal. However, as far as I know, these parameters are not provided by the function. Is there any way to obtain them?  Also, this function is using a non-linear least squares (fast=FALSE), so is there any way to get the parameters of this method? 

Thank you for the help!

**Comment by ericpre** [comment]
No, currently you can't the fitting error using the `remove_background` method.

However, you can get by using a model:
```python
from hyperspy import components1d

pl = components1d.PowerLaw()
pl.A.value = 1e5
pl.r.value = 1.
s = hs.signals.EELSSpectrum(pl.function(np.arange(100, 200)))
s.axes_manager[0].offset = 100
s.add_poissonian_noise()

m = s.create_model()
m.set_signal_range(110, 150)
m.fit()
```

Then you can access some error estimation metrics using `m.red_chisq`, `m.chisq` or the standard deviation of the parameters

More on this in the documentation:
http://hyperspy.org/hyperspy-doc/current/user_guide/model.html#least-squares-with-error-estimation

It would be good to return the error estimation, possibly only in "non-interactive" mode since the operation is not performed in place and it does return something (the background subtracted signal), so we could also return the error estimation at the same time.

**Comment by francisco-dlp** [comment]
Good point, maybe it could return the ``Model`` instance, since that contains the info. Also, it will be good to display the reduced chisq in the remove background GUI, as it can help with being a bit more objective when choosing the fitting region.

**Comment by ericpre** [comment]
This is done in #2307.
