### ISSUE TITLE
Cannot run the following python3 code on macbook

### ISSUE THREAD

**Issue by rainagyw** [hyperspy/hyperspy#2241]
Hi, I cannot run the following code on my mac book.
import sys
import matplotlib
matplotlib.use('Qt4Agg')

import hyperspy.api as hs
your_image = hs.load(sys.argv[1]) 
your_image.plot()

what could be the reasons?
Thanks

**Comment by jat255** [comment]
@rainagyw it looks like you're trying to run this script as a one-off from the command line? What sort of output are you receiving (any errors)? I'm not overly familiar with Mac, but we usually do `matplotlib.use('qt')` rather than `Qt4Agg` (Qt4 is quite an old version of Qt) - from an interactive jupyter notebook or console, you would use `%matplotlib qt`.

**Comment by rainagyw** [comment]
Hi, this is the error I got after changing it to 'qt'. BTW, what is your version for hyperspy and 
matplotlib, respectively?

Here is the code:
import sys
import matplotlib
matplotlib.use('qt')
import hyperspy.api as hs
your_image = hs.load(sys.argv[1]) 
your_image.plot()

Here is the error:
Traceback (most recent call last):
  File "test_hs.py", line 3, in <module>
    matplotlib.use('qt')
  File "/Users/yuwei/miniconda/envs/python3/lib/python3.6/site-packages/matplotlib/__init__.py", line 1396, in use
    name = validate_backend(arg)
  File "/Users/yuwei/miniconda/envs/python3/lib/python3.6/site-packages/matplotlib/rcsetup.py", line 268, in validate_backend
    return _validate_standard_backends(s)
  File "/Users/yuwei/miniconda/envs/python3/lib/python3.6/site-packages/matplotlib/rcsetup.py", line 72, in __call__
    % (self.key, s, list(six.itervalues(self.valid))))
ValueError: Unrecognized backend string "qt": valid strings are ['GTK', 'GTKAgg', 'GTKCairo', 'GTK3Agg', 'GTK3Cairo', 'MacOSX', 'nbAgg', 'Qt4Agg', 'Qt4Cairo', 'Qt5Agg', 'Qt5Cairo', 'TkAgg', 'TkCairo', 'WebAgg', 'WX', 'WXAgg', 'WXCairo', 'agg', 'cairo', 'gdk', 'pdf', 'pgf', 'ps', 'svg', 'template']

**Comment by jat255** [comment]
Perhaps try `'Qt5Agg'`? There's also a `'MacOSX'` backend, but it sounds like that might need a "framework" build of python, which is something specific to Macs that I am unfamiliar with. I also found this: https://matplotlib.org/3.1.0/faq/osx_framework.html

Personally, I use v1.5.1 of HyperSpy and 3.1.1 of matplotlib without issue on my Linux machine.

**Comment by jat255** [comment]
Also, if you're trying to interactively examine data, you're probably better off using the Jupyter notebook interface, rather than writing individual scripts (as described in the [user guide](http://hyperspy.org/hyperspy-doc/current/user_guide/getting_started.html#starting-python-in-linux-and-macos))

**Comment by rainagyw** [comment]
Hi, I tried to use jupyter notebook and it works. Thanks.
