### ISSUE TITLE
Loading .pts EDX files (JEOL format)

### ISSUE THREAD

**Issue by yy-ssang** [hyperspy/hyperspy#2257]
Hello. I am Sang-Hyeok Yang in SungKyunKwan University(SKKU, South Korea).

I'm a new user using hyperspy, and I want to process EDX data.
In hyperspy, .msa file and .rpl file can be opened as EDX data. But I have EDX data as .pts file(JEOL).

So, Does anyone have an idea to load .pts file? or convert .pts file to .msa or .rpl file??

Thank you.

**Comment by yy-ssang** [comment]
![image](https://user-images.githubusercontent.com/55566364/65293482-576f4c80-db96-11e9-96a5-3fd46a722fd2.png)

This is error message when I use hs.load() to load .pts file

**Comment by jat255** [comment]
Thanks for the report Sang-Hyeok. HyperSpy does not support `.pts` files natively. The `load` function is trying to use a reader that is not designed for that file type, which is why it is failing.

Depending on the format specifications, it would not be too difficult to write a reader to add support for them, but I don't think anyone on the development team has worked with these files before. If you could share the file, or perhaps have a specification for the format from JEOL, that would be very helpful. 

Alternatively, to just read your data, if you can export the file into any ASCII-style format from the JEOL software (like txt, csv, etc.), it is generally not too difficult to get that sort of data into HyperSpy using Numpy's file reading tools (see http://hyperspy.org/hyperspy-doc/current/user_guide/getting_started.html#loading-data for creating a signal from a Numpy array).
