### ISSUE TITLE
Signal events don't trigger on data_changed

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#2286]
I expect that when I have connected the `s.events.data_changed` event to a function, it triggers on a manual change to `s.data`. Currently, this doesn't happen. Am I using it wrong?

This is best shown with an example:
```python
import hyperspy.api as hs
s = hs.signals.Signal1D([[1,2,3], [1,2,3]])
def data(obj):
    print('data')
    
s.events.data_changed.connect(data)
s.data[:] = 2 # should print 'data' but doesn't
s.events.data_changed.trigger(s) # prints 'data'

def axes(obj, index):
    print('axes')
s.axes_manager.navigation_axes[0].events.index_changed.connect(axes)
s.axes_manager.indices = (1,) # prints 'axes'
```
I believe this is due to the lack of a trigger in the [`s.data` setter](https://github.com/hyperspy/hyperspy/blob/4d78e626b5c447a0e5ddbabef0b1763d63d65d94/hyperspy/signal.py#L1822). Compare with the equivalent for the [`s.axes_manager.indices`, where there exists a trigger.](https://github.com/hyperspy/hyperspy/blob/4d78e626b5c447a0e5ddbabef0b1763d63d65d94/hyperspy/axes.py#L1432)

https://github.com/hyperspy/hyperspy/blob/4d78e626b5c447a0e5ddbabef0b1763d63d65d94/hyperspy/signal.py#L1822

I noticed this when trying to put together an events function plotting multiple ROIs for @kociak on [gitter](https://gitter.im/hyperspy/hyperspy?at=5dd4f5deedec8e6c1aae2d3b)

**Comment by thomasaarholt** [comment]
Hm, I guess there may not be a mechanism available here, since `data[:]` belongs fully to numpy and we won't have a way to hook an event in there?

**Comment by ericpre** [comment]
According to the `data_changed` event documentation, this behaviour is intended.

Adding a setter for the data attribute triggering a `data_changed` event would most likely not help when you do `s.data[:] = something`, because of the difference between `s.data[:] = something` and `s.data = something`, but I haven't checked.

If you find a situation, when the `data_changed` event is not triggered when it should, please re-open.
