### ISSUE TITLE
plot EDS hypermap from .bcf

### ISSUE THREAD

**Issue by iceaiai** [hyperspy/hyperspy#2349]
I have loaded the bruker hypermap data in the notebook. Somehow I could not plot it. I just verify the plot function works fine for .emi file from FEI. My microscope is Hitachi HD2700 STEM. I am wondering whether we could not plot it in the bcf file. Could you please help me to fix it out? @sem-geologist 

Here is my code:
```python
%matplotlib qt
import hyperspy.api as hs
import numpy as np
import matplotlib.pyplot as plt
s = hs.load("1.bcf")
s.plot()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-9-886abc61b753> in <module>
----> 1 s.plot()

AttributeError: 'list' object has no attribute 'plot'
```

**Comment by ericpre** [comment]
Depending on the number of signals (images, spectrum images, etc.), the `load` function will return a hyperspy signal (only one image or spectrum image) or a list of signals (if there are several) - please check the docstring of the `load` function.
In your case, the error message says that you have a list, so you need to index the signal you want from the list; for example: `s[0].plot()`

**Comment by iceaiai** [comment]
Thanks to reply. The issue has been fixed by specify the spectrum image in 'select_type'

**Comment by ericpre** [comment]
Glad to see that you have got it working.

For completeness and/or future reader: the issue here is to try to "plot" of a python list (the `AttributeError: 'list' object has no attribute 'plot'` error).
The hyperspy `hs.load` function can return a list of signal or a signal; when the `signal_type` parameter of the `load` function is specified, it may happen (not always) that only a single hyperspy signal will be returned, as this seems to be the case here.

The most robust approach to deal with this is to make sure to call the `plot` (or any other method/functions) to the right object (here a python list versus a hyperspy signal).
