### ISSUE TITLE
Error while importing a spc file

### ISSUE THREAD

**Issue by bagel897** [hyperspy/hyperspy#2426]
Hello!  
I've been trying to import a .spc file by doing this  
`data = hs.load("data/RamanSpec.spc",signal_type="EDSSEMSpectrum")`    
but I get the following error  
`OverflowError: memory mapped length must be positive`

**Comment by thomasaarholt** [comment]
Hi @bageljrkhanofemus, could you upload an example file?

**Comment by bagel897** [comment]
https://1drv.ms/u/s!Aiu1SnKwsB5fqX-Ts8nX_iRXB_5N?e=9pNRul

**Comment by jat255** [comment]
@bageljrkhanofemus I haven't looked at the file structure in detail, but the only type of .spc file that's supported by HyperSpy is a single spectrum EDS file as written by the EDAX TEAM software. I don't know what software writes the Raman spectrum you linked, but I would not expect our reader to be able to parse it, since the internal structure is probably different.

**Comment by bagel897** [comment]
In that case, I will use another format.
