### ISSUE TITLE
Signal type warnings

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#2433]
#2425 (@tjof2), which fixes #1584, makes a lot of signal operations output the warning:
```python
WARNING:hyperspy.io:`signal_type=''` not understood. Setting signal type to `Signal1D`
```
It's easily testable by
```python
import hyperspy.api as hs
s = hs.signals.Signal1D([1,2,3])
m = s.create_model()
```
The test suite, in particular, outputs a large number of warnings, but it's also confusing the user.
Additionally, the signal type isn't actually set to anything afterwards, as far as I can see?

There are a couple of ways to resolve this:
- roll back the related changes and only give a warning if the user sets `s.set_signal('non_existing_signal_type')`, as originally intended by #1584 
- Automatically fill the signal type with the respective type (Signal1D, LazySignal1D, etc). Might need logic to convert the `signal_type` of `LazySignal1D.compute()` from LazySignal1D to Signal1D)

**Comment by francisco-dlp** [comment]
I would go for your first option plus making the warnings more informative. ``signal_type`` has nothing to do with the signal dimensions. When ``signal_type`` is the empty string, the right signal subclass is assigned according only to the signal dimension. Otherwise, it tries to find a signal subclass specialized on that particular signal type first with the right signal dimension. So, the signal type should not be anything like ``signal1D``.

I think that the warnings must be more informative because:

* These days many signals are provided by external packages and, if the package is not installed, the user will get a warning and won't know how to fix it.
* Sometimes the user may have misspelled a known signal type. It'll be good to point them to ``hs.print_known_signal_types()`` so that they can check which are the known signal types.
* Even if the signal type is not known to hyperspy with all external providers installed, I think that it is fine to set it to describe the dataset. Say somebody sets it to ``LIGO``. There is no external package that I know that currently provides specialized signals for this sort of data, but at least we'll know what the data is about by inspecting the metadata.

**Comment by tjof2** [comment]
Yeah good catch @thomasaarholt (though in my defence, logger-type warnings only show up when tests fail :smiley: ). Will fix now.

**Comment by thomasaarholt** [comment]
> Yeah good catch @thomasaarholt (though in my defence, logger-type warnings only show up when tests fail 😃 ). Will fix now.

Hahahaha, indeed :D
