### ISSUE TITLE
Clarify the usage of `remove_signal_range(None)`

### ISSUE THREAD

**Issue by cmeyer** [hyperspy/hyperspy#2516]
It would be useful to have `clear_signal_range` or `reset_signal_range(False)`.

Then multiple ranges could be added with `add_signal_range`. Otherwise, one must call `set_signal_range` for the first range and `add_signal_range` for remaining ranges.

The workaround is to just clear `channel_switches` directly.

**Comment by ericpre** [comment]
> It would be useful to have `clear_signal_range` or `reset_signal_range(False)`.

Is the [`reset_signal_range`](https://hyperspy.readthedocs.io/en/latest/api/hyperspy.models.model1d.html#hyperspy.models.model1d.Model1D.reset_signal_range) method not doing that?

> Then multiple ranges could be added with `add_signal_range`. Otherwise, one must call `set_signal_range` for the first range and `add_signal_range` for remaining ranges.

Agree, that it would be convenient to set the signal range for several ranges, in particular in combination with ROIs.

Since the whole signal "is on" by default it may more logical and/or straighforward to use the `remove_signal_range` instead of a combination of `set_signal_range` and `add_signal_range`. For example, this is what the what the `fit_background` method of the `EDSModel` does:
https://github.com/hyperspy/hyperspy/blob/742a95fecff957eca714c98db2ae51decace95f9/hyperspy/models/edsmodel.py#L375-L381

**Comment by ericpre** [comment]
@cmeyer, does it cover your suggestions? If so, can you update the title to something more suitable or close this issue?

**Comment by cmeyer** [comment]
The existing `reset_signal_range` sets the values to `True`. Making additional calls to `add_signal_range` have no effect since all the values are already `True`.

If I have a signal and want to remove two overlapping ranges or two non-overlapping ranges, the logic for creating `remove_signal_range` calls is complex.

**Comment by ericpre** [comment]
By default the whole fitting range is _on_ and `reset_signal_range` reset to this default value. From a method named `clear_signal_range` I would expect to clear the signal range as in set it to the default. From your comments, it sounds like you want something to set all channel _off_ because using the word _clear_ to do this is confusing (no clear at all...)!

> If I have a signal and want to remove two overlapping ranges or two non-overlapping ranges, the logic for creating `remove_signal_range` calls is complex.

I don't see where is the complexity, you can iterate over the ranges you want to remove regardless if they are overlapping or not. If you provide a minimum example to reproduce it would help to clarify. Alternatively, you can send a PR to implement your suggestions. In both cases, it would easier to make sure, we are talking about the same thing.

**Comment by cmeyer** [comment]
> I don't see where is the complexity, you can iterate over the ranges you want to remove regardless if they are overlapping or not. If you provide a minimum example to reproduce it would help to clarify. Alternatively, you can send a PR to implement your suggestions. In both cases, it would easier to make sure, we are talking about the same thing.

I'm trying to *add* signal ranges after disabling all channels, not remove them after enabling all channels.

Maybe I'm missing something. If I have 3 ranges (r0, r1, r2) that I want enabled and everything else disabled, how do I accomplish that with the existing API?

```
# all channels are already enabled by default
signal.reset_signal_range()  # sets them to enabled, which is already the case
# signal.clear_signal_range()  # this is the function I want.
# these statements don't do anything since all channels are already enabled.
signal.add_signal_range(*r1)
signal.add_signal_range(*r2)
signal.add_signal_range(*r3)
```

**Comment by ericpre** [comment]
The following should work for what you want:
```python
import numpy as np
import hyperspy.api as hs

s = hs.signals.Signal1D(np.arange(1024))
m = s.create_model()
m.remove_signal_range(None)

signal_range_list = [[100*i, 100*i+50] for i in range(3)]
for signal_range in signal_range_list:
    m.add_signal_range(*signal_range)

print(m.channel_switches)
```

When using `m.remove_signal_range()` without argument, the GUI will pop up and in the example above, there will be no GUI because it sets the first value to None (`m.remove_signal_range(None)`).The usual pattern to disable the use the method interactively is to set the values explicitly, here it should be the first and last channel values. However, only setting `None` for the first argument is more simple, but I think that this is more of a fortunate workaround rather than an intended behaviour. This is not documented and I am not sure if this is a good syntax to rely on at the moment...

**Comment by ericpre** [comment]
Note that if you are using the release version you will hit this ancient bug: https://github.com/hyperspy/hyperspy/issues/2457.

The easiest is possibly to use `m.channel_switches[:] = False`.

**Comment by cmeyer** [comment]
I'll close this bug -- there are multiple workarounds. But it might still be nice to have `clear_signal_range`.
