### ISSUE TITLE
warnings message when setting background parameters to 'not free'

### ISSUE THREAD

**Issue by patquem** [hyperspy/hyperspy#2628]
Hello,

Here is a short test case that reproduce the problem I observe in a more complicated one.

```
import hyperspy.api as hs

s = hs.datasets.eelsdb(title="Hexagonal Boron Nitride", spectrum_type="coreloss")[0]
m = s.create_model()
# m[0].set_parameters_not_free(['A', 'r'])
m.smart_fit()
```

When uncommenting the line with `set_parameters_not_free` function, 2 warnings appear :

> WARNING:hyperspy.model:Covariance of the parameters could not be estimated. Estimated parameter standard deviations will be np.nan.
> WARNING:hyperspy.model:`m.fit()` did not exit successfully. Reason: Improper input parameters.

Would it be possible to prevent these warnings ?
Thanks,
Patrick

**Comment by ericpre** [comment]
```python
import hyperspy.api as hs

s = hs.datasets.eelsdb(title="Hexagonal Boron Nitride", spectrum_type="coreloss")[0]
m = s.create_model()
m[0].set_parameters_not_free(['A', 'r'])
m.smart_fit()
```

@patquem, this warning is normal because `smart_fit` fit the background first and the folllowing component in a cascade fashion. Since the parameters of the background component are fixed, the first fit will fail and rightly raise a warning.

The following example shows more precisely that the fit fails as expected and why a warning is justified:
```python
import hyperspy.api as hs

s = hs.datasets.eelsdb(title="Hexagonal Boron Nitride", spectrum_type="coreloss")[0]
m = s.create_model()
m.plot()
m[0].set_parameters_not_free(['A', 'r'])
m.fit_background()
```

If you have an another example you can provide where the fit works and it raises a warning, please re-open.

**Comment by ericpre** [comment]
@JMorzy have mentioned something similar with warning: https://gitter.im/hyperspy/hyperspy?at=5fbe7fbebba6a3778b804b70

> Since I updated my hyperspy recently, when using the remove_background() or fit_component() with the PowerLaw component, I keep getting the following warning 'WARNING:hyperspy.model:Covariance of the parameters could not be estimated. Estimated parameter standard deviations will be np.nan.
WARNING:hyperspy.model:m.fit() did not exit successfully. Reason: Number of calls to function has reached maxfev = 600.' It was not there before and it seems to fit poorly, any ideas of how I can improve this? It doesn't take maxfev argument, so perhaps needs changing of the default maxfev value in the code itself?

@JMorzy did you figure out if the warning was valid or not? If not, can you provide an example to reproduce?

**Comment by patquem** [comment]
Hello,
Thank you @ericpre for your answer.
In fact, `m[0].set_parameters_not_free(['A', 'r'])` is related to the fact that the background in our script has been already fitted in a  previous step. That is the reason why, we don't want the background to be re-evaluated with `smart_fit`.
In a sense where user put **intentionally** `set_parameters_not_free` , warning message related to this should not be written on my mind. 
In the present case, with our background calculation strategy we are faced to so many and unwanted warning message during hyperspy execution :(

**Comment by ericpre** [comment]
In its current implementation, `smart_fit` is running the `fit_background` method and it make sense to warn the user when the background is attempted to be fitted with the corresponding fitting parameter not free.

> In fact, `m[0].set_parameters_not_free(['A', 'r'])` is related to the fact that the background in our script has been already fitted in a previous step. That is the reason why, we don't want the background to be re-evaluated with smart_fit.
In a sense where user put intentionally set_parameters_not_free , warning message related to this should not be written on my mind.

> In fact, `m[0].set_parameters_not_free(['A', 'r'])` is related to the fact that the background in our script has been already fitted in a previous step. That is the reason why, we don't want the background to be re-evaluated with `smart_fit`.
> In a sense where user put **intentionally** `set_parameters_not_free` , warning message related to this should not be written on my mind.

It sounds like the `smart_fit` is not suitable for your use case and I see two options:
- change how you use the `smart_fit` in your workflow
- add a `fit_background` parameter to the `smart_fit` method. I am not aware of cases, where it would be beneficial.

What is the issue with letting the background free when calling `smart_fit`?

> In the present case, with our background calculation strategy we are faced to so many and unwanted warning message during hyperspy execution :(

Are all these warning related to the call of the `fit_background` method? If not, it would be good to figure if these warning are justified or not.

**Comment by Florian-Castioni** [comment]
Hello @ericpre 

I complete the answer of @patquem. The idea here is to force the background to be correctly fitted before doing the entire fit using `smart_fit`. The following images show the interest : the Ge L theoretical edge do not fit well on the experimental edge, and the fit find a solution by changing the background parameters, wich is not suitable. Here, we need to "force" the background to stay fitted, which is made by using `m[0].set_parameters_not_free(['A', 'r'])` the line.

![image](https://user-images.githubusercontent.com/69305511/110970942-8b29cd80-835a-11eb-85a7-6955d743d532.png)
![image](https://user-images.githubusercontent.com/69305511/110971112-bf04f300-835a-11eb-937f-144c10d31ae0.png)

In that particular case, a simple `fit()` would be enough to avoid the warning, but in other situations with several elements, the `smart_fit()` function is still needed.  

The warning would not be annoying if it would be appeared just once ; but using this procedure on a hypermap does print a massive number of warning lines.

As you mentionned, I think the best option woulb be to add an option to `smart_fit`, or to block the warning message when setting parameters not free.

**Comment by francisco-dlp** [comment]
@Florian-Castioni, the whole point of ``smart_fit`` (and EELS curve fitting in general) is fitting the background and the edges on  the whole energy range. Fitting the background only before the edge onset is akin of removing it so then, why not simply using the windows (aka Egerton) method?

I find it strange that the fit to the Ge L edge is so poor. Have you enabled the fine structure in the EELS CL edges?

**Comment by ericpre** [comment]
Indeed, removing the background before sounds more sensible than adding an optional parameter to `smart_fit` as I suggested earlier!

I came across this behaviour with the Ge-L edge before and I don't remember if I found an explanation or not! Plural scattering will contribute to it but I am not sure if it will explain such a disagreement...
On a side note: how do you know that the background is correct and the Ge edge is not?

**Comment by Florian-Castioni** [comment]
Thank you @francisco-dlp and @ericpre for your answers. 

Indeed, removing the background from the window method is maby the best approach. One of the reason why I wanted to force the fit of the background is because Digital Micrograph seems to adopt this method, and I was quite satisfied by these results. For this kind of energy range, I think a potentiel error of fit comes from the mismatch of the theoretical edges, and not from the background extrapolation which is quite accurate. 

The fine structure was not activated in that case (even if I tried), beacuse the mismatch do not come from the first energy range of the edge, but on the entire energy range, as you can notice. Note that I carefully meausred the convergence and collection angle to compute Ge-L edge cross-section. This behavior of the theoretical Ge-L edge was observed for many different experimental configurations (especially with different collection angles).

Indeed @ericpre I made the assumpation that, on this range of (high) energy-loss, the power law fits quite well. I quickly checked this assumption on a Si/SiGe sample, from an area without Ge (Si zone) where the power law was perfectly fitting experimental curve. You could imagine that changing the chemical composition (i.e. measuring the Ge edge on SiGe) does change the parameters of the background power-law, but I think we keep the fact that the extrapolation of the background is still correct on this energy range.
