### ISSUE TITLE
Clarify if interactive ROIs will be added to navigation or signal dimensions

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#2630]
It is a bit unclear on which plot of a signal (navigator or signal plot) that an interactive ROI will be added to.

Testing it manually, it seems that they are added to the first dimension (or pair of dimensions) that will contain the ROI. A Signal2D with shape (5, | 5, 5) won't add a CircleROI to the navigator, but will add a SpanROI there.

To me it would be more intuitive if the ROI by default got added to the Signal plot (unless it can't fit). But that may not be convenient for the default way of operating on EELS / EDS spectrum images.

Regardless, we should document it better than the [current version](http://hyperspy.org/hyperspy-doc/current/user_guide/interactive_operations_ROIs.html), which doesn't mention this, and also think about adding an option to specify if it should be added to the navigator or signal.

The example for CircleROI and SpanROI:

```python
%matplotlib widget
import numpy as np
import hyperspy.api as hs

s1 = hs.signals.Signal2D(np.random.random((5, 20, 20)))

# works
cr = hs.roi.CircleROI(10,10, 5)
sr = hs.roi.SpanROI(left=2., right=3.)

roi1 = [cr, sr]

s1.plot()
for i, roi in enumerate(roi1):
    roi.interactive(s1,)
```
![image](https://user-images.githubusercontent.com/2721423/106261281-a6fd6800-6221-11eb-94ea-f5004cd9803a.png)

**Comment by ericpre** [comment]
Agree, this is poorly documented: in the [user guide](http://hyperspy.org/hyperspy-doc/current/user_guide/interactive_operations_ROIs.html#region-of-interest-roi), there is a link to the [interactive method](http://hyperspy.org/hyperspy-doc/current/api/hyperspy.roi.html#hyperspy.roi.BaseInteractiveROI.interactive) but the docstring is too cryptic... and I am not sure I understand it fully... By default, the ROI is added to the navigation space if this is possible and I guess, in your example above, the `CircleROI` is added to the signal space because of the axes mismatch with the navigation space.

**Comment by thomasaarholt** [comment]
> By default, the ROI is added to the navigation space if this is possible

That makes sense, I guess. ~~I was originally thinking that it should add to the signal space because of the examples in the docs.~~
Looks like the docs' example images actually do cover both. I'm fine with the default being trying to go on the navigator.

**Comment by ericpre** [comment]
Does anything needs to be done here, or can it be closed?
