### ISSUE TITLE
Mapping of lazy signals with chunksize 1 at the last axis of the navigation axis 

### ISSUE THREAD

**Issue by ptim0626** [hyperspy/hyperspy#2748]
Mapping of lazy signal seems not working if the chunk of the last axis of the navigation axes is 1 or (size mod chunk) is 1:

```python
import numpy as np
import dask.array as da
import hyperspy.api as hs

def f(p):
    return np.array([1,2,3])

s = hs.signals.Signal2D(da.random.random((10, 15, 32, 32))).as_lazy()
s.rechunk(nav_chunks=(1, 1))
ss = s.map(f, inplace=False, parallel=False, ragged=True)
ss.compute()
```
Same for `nav_chunks=(1, 2)` 
```python
s.rechunk(nav_chunks=(1, 2))
ss = s.map(f, inplace=False, parallel=False, ragged=True)
ss.compute()
```
It gives 
```python
IndexError: tuple index out of range
```
when computing the dask array. This will print out all failed chunks at the last dimension of the navigation axis.
```python
for k in range(1,16):
    try:
        s.rechunk(nav_chunks=(1, k))
        ss = s.map(f, inplace=False, parallel=False, ragged=True)
        ss.compute()
    except IndexError:
        print(k)
```
gives
```python
1
2
7
14
```

Is this the expected behaviour?

**Comment by magnunor** [comment]
This is not expected behaviour, and is a bug.

I managed to track down the reason for this, it is due to the `output_array = output_array.squeeze(-1)` in `process_function_blockwise`: https://github.com/hyperspy/hyperspy/blob/RELEASE_next_minor/hyperspy/misc/utils.py#L1238

I'll make a pull request with a bug fix.
