### ISSUE TITLE
assign_subclass and signal with one value?

### ISSUE THREAD

**Issue by magnunor** [hyperspy/hyperspy#2766]
In https://github.com/hyperspy/hyperspy/pull/2703, one of the tests is failing due to how `s._assign_subclass` works.

Essentially, should a signal with one value be a `BaseSignal`, or a `Signal1D`? Currently, `_assign_subclass` turns a signal with one value into a `Signal1D`, but the test expects it to be a `BaseSignal`.

To replicate this:

```python
s = hs.signals.BaseSignal(1) # <BaseSignal, title: , dimensions: (|1)>
s._assign_subclass() # <Signal1D, title: , dimensions: (|1)>
```
The question is then which signal type _should_ a signal with one value be? `BaseSignal` or `Signal1D`?

**Comment by jlaehne** [comment]
I would have thought that `BaseSignal` is just a parent class for all other signal classes, but is normally not used. `Signal1D` provides many additional routines, but then most of them don't make sense on a signal with one value only. So it seems to me to indeed be an edge case.

**Comment by thomasaarholt** [comment]
If the array is a zero-dimensional array, then I'd say it should probably go to basesignal or a "Signal0D".

**Comment by francisco-dlp** [comment]
HyperSpy does not support array scalars (i.e. 0-dimensional arrays) because scalar arrays, unlike ndarrays, are immutable. That's why HyperSpy converts any array scalar in a 1D array of shape `[1]`.

This is indeed a corner case. Considering that, as pointed out by @jlaehne, most ``Signal1D`` methods make no sense for 1-element arrays, I think that it'll be better to assign them to ``BaseSignal``.

**Comment by ericpre** [comment]
Done in #2773.
