### ISSUE TITLE
Nexus file save/load two signals return

### ISSUE THREAD

**Issue by magnunor** [hyperspy/hyperspy#2779]
When saving and loading a `nxs` style HDF5 file in HyperSpy, an extra signal is returned. Example:

```python
import numpy as np
import hyperspy.api as hs
s = hs.signals.Signal1D(np.random.random((20, 1000)))
s.save("test_nexus.nxs")
s_load = hs.load("test_nexus.nxs")
```

`s_load` is a list of two signals:
```python
[<Signal1D, title: unnamed__0, dimensions: (20|1000)>,
 <BaseSignal, title: entry1_unnamed__0_data, dimensions: (1000, 20|)>]
```

Is this intended behaviour?

**Comment by ericpre** [comment]
Indeed, this is odd!
@ptim0626, you will know better on this file format, can you please advise?

**Comment by ptim0626** [comment]
ah yes I would say this is a bug, same dataset is loaded twice.

The reason is that the loader loads both NeXus dataset and HDF5 dataset without `nxdata_only=True`, and a NeXus dataset is also an HDF5 dataset, so it gets loaded twice. If it is specified with `nxdata_only=True`, only the NeXus dataset will be loaded.

This is obviously not nice and I will provide a fix for this shortly: avoid loading the same dataset twice whether `nxdata_only` is True or False. Thanks for spotting this!
