### ISSUE TITLE
How to include new generalised oscillator strength dataset

### ISSUE THREAD

**Issue by gguzzina** [hyperspy/hyperspy#2815]
We (at CEOS GmbH, together with the team of Prof. Kohl at the University of Münster) are working on computing a new database of Generalised Oscillator Strengths.
As this is long standing nuisance for people who want to perform quantitative EELS analysis, we think including support for it in hyperspy is a good idea.

The results we are getting for the moment are quite encouraging, but the dataset is not yet ready to be released. Still, I think it's a good time to gather technical ideas on how to do this.

My current proposal is to include data for all edges, appropriately downsampled, in a HDF5 archive.
When compared with the existing dataset, they cover a much higher "field of view" in both energy and momentum, and have better sampling on top of that, so it is a much larger dataset.
Nevertheless, at ~40MB it's not obscenely big by modern standards.

The HDF5 archive would then be distributed, probably by uploading it on Zenodo.

I would then write a new GOS class, probably a subclass of HartreeSlaterGOS, to use the new data, and also include patches to the hyperspy configuration dialog to let users select the file path.

Ideas and suggestions are very welcome. Does anyone have different preferences for the format of the dataset?
The discussion on the preferred way to distribute the data is ongoing with the team of Prof. Kohl, but ideas are welcome in that area as well.

**Comment by gguzzina** [comment]
A little sneak peek :-) 
![25_Mn_L_0 005mrad](https://user-images.githubusercontent.com/63253/130943780-dbf42ed9-4fac-4ddb-a2c5-467a904d6054.png)

**Comment by ericpre** [comment]
This sounds brilliant, I am sure many people will be looking forward this, me being the one!

> As this is long standing nuisance for people who want to perform quantitative EELS analysis, we think including support for it in hyperspy is a good idea.

Ineed, this is definitively a long standing issue!

A few thoughts about the technicalities:
- zenodo sounds very good
- I don't know if there is any standard specification for storing GOS dataset. If there isn't one, hdf5 with your own specifications would fit very well for the need here
- in hyperspy, I suspect that we should start using [pooch](https://www.fatiando.org/pooch) for downloading "large" test files and the implementation of this GOS component should use it. Since a few years, pooch seems to be well established in the python scientific community: it is used by scikit-image and co, which means that there is a community to support and it should be around for a while!
- we will need to keep track of the version of the dataset in the model component and being able to specify the version of dataset, when creating the model component to ensure reproducibility of the analysis.
- it may be good to have a github repository containing a few example simple scripts/notebooks showing how to use the dataset. It would also be good for traceability, make update, etc. Typically, once zenodo can be setup (takes a few minutes) to mine a DOI and archive the DOI when a github release is created. It may be a bit overkill here but I find it very good for traceability reasons and if this is possible to also host the source to generate the dataset in this repository, this would be very good too. Obviously, this would lower the barrier for researchers with interests on improving the GOS to work on this!

@hakonanes, is pooch a good option to retrieve datasets? Is there anything you would like to comment on its use?

**Comment by hakonanes** [comment]
I can indeed recommend pooch for larger files! Following what scikit-image are doing, I found it easy to implement a [kikuchipy.data](https://kikuchipy.org/en/latest/reference.html#module-kikuchipy.data) module with some datasets packaged with kikuchipy, while some are retreivable from a GitHub repo [kikuchipy-data](https://github.com/pyxem/kikuchipy-data).

We have some more information in our [contributing guide](https://kikuchipy.org/en/stable/contributing.html#adding-data-to-the-data-module) explaining how the `data` module works in kikuchipy. Note that I added the `allow_download` parameter when loading datasets not included in the package, since I found it safest to let the user specify explicitly that they want to download an external dataset to their local cache via kikuchipy by setting it to `True`. Otherwise it would just start downloading the dataset without asking the user.

**Comment by gguzzina** [comment]
Thanks a lot for the feedback. I will start looking into pooch.

> I don't know if there is any standard specification for storing GOS dataset.

It doesn't look like there are too many around at the moment :-)
For now I am simply creating a group for each element, containing a dataset (a 2D array) for each edge. The q and E axes are stored as attributes to each dataset.

> we will need to keep track of the version of the dataset in the model component and being able to specify the version of dataset, when creating the model component to ensure reproducibility of the analysis.

This is a good point I had not thought about. I suppose one way could be by including the Zenodo DOI both in the HDF5 file and as a property of the model component. This way it is always possible to trace back to the correct dataset in a univocous way. However I did not look at all at how the models are exported right now.

Edit: I like the idea of including the DOI in the data file so that we know the source even for data which may just have been copied over from a colleague. A hash would ensure that two files are the same, but not where they came from.

> if this is possible to also host the source to generate the dataset in this repository, this would be very good too

It would indeed be very nice to share the source codes, but a few of the files came with strings attached. We will try to untangle these if there is sufficient interest from all parties involved. But it does not depend solely on me, and success is not guaranteed as I also do not have the skills needed to replace these files, if it comes to that.

**Comment by ericpre** [comment]
> I suppose one way could be by including the Zenodo DOI both in the HDF5 file and as a property of the model component.

If I remember correctly, it will not be possible to include it in the hdf5 file, the typically egg and chicken issue: you can't include the reference of the archive _in_ the archive itself!

> It would indeed be very nice to share the source codes, but a few of the files came with strings attached. We will try to untangle these if there is sufficient interest from all parties involved. But it does not depend solely on me, and success is not guaranteed as I also do not have the skills needed to replace these files, if it comes to that.

Yes, I can imagine that this is not trivial or possible even if I don't know the details, but I thought that it would be worth mentioning it and maybe at some point, it will be possible! In any case, having a good system in place for distributing the dataset will already be a significant improvement over the current situation.

**Comment by gguzzina** [comment]
> If I remember correctly, it will not be possible to include it in the hdf5 file, the typically egg and chicken issue: you can't include the reference of the archive _in_ the archive itself!

Actually on Zenodo you can reserve the DOI for the data deposit before you even start to upload any file. This DOI represents the entire record, and not the specific file. But as far as I can tell Zenodo does not offer per-file DOIs anyway.
So it is a little extra work:
- Start drafting the data deposit and reserve the DOI
- Modify the HDF5 file to include the DOI 
- upload

Still I think it should be doable.

**Comment by ericpre** [comment]
OK, sounds good then!

**Comment by gguzzina** [comment]
Hello, I'd like a few opinions on the file format.
I'm undecided between an HDF5 file with a structure of the type:
[Ti]/[L23] with [L23] being a data table and extra extra information (E and q axis) being attributes of the table itself.

Or a gzipped file containing a similar folder structure:
Ti/L23/gos.txt with further data stored as extra files in the folder.

The first one is more compact (~22MB vs 33MB) while the second one is more human-readable, but for most practical purposes they are equivalent.

Further data would be included as extra tables (json files).
In my case this would a table clarifying naming conventions and certain weighing coefficients ( similar to issue 2817 ), as well as the quantum numbers that identify each edge table.

Finally a [metadata] table (or a metadata.json file) with some information such as a DOI, authors, basic description of computation method, possible bibliographic information, and finally a description of the data contained in the various tables.

The part I'm struggling with is how to make this all extendable. Suppose a year or two from now someone else wants to compute a GOS that better includes spin-orbit coupling, or maybe better fine structure, or difference valence states.

How do we speficy a file format that still allows all that to happen?
Does anybody here have any idea?

**Comment by ericpre** [comment]
> How do we speficy a file format that still allows all that to happen?

I am not sure if I understand correctly the issue, but I will try to give an answer!
Each time there is a change in the dataset, the version of the dataset should be increased. In case of hdf5 file, some formats specify a file version as an attribute, typically named `version` and located in the root of the file.
Regarding the structure of the file, obviously, it would good to avoid changing its structure between version therefore it is useful to think about what could be added in the future in order to design a future proof structure. Nevertheless, the structure of the file itself can change and if you choose to follow [semantic versioning](https://semver.org), you could increase the major or minor version to indicate incompatible API ("structure" of the dataset) changes.
To keep a record over time and make it easy for other to follow what are the changes, maybe it would be good if there was a public git repository on github, gitlab, etc and this repository could contains more information targeted at advanced users or developer in a readme, for example. This repository could contains a text or markdown file which describe the format itself along with a changelog.

Regarding how HyperSpy will deal these different GOS (from GMS and this one to start with) and file versions is a different story, but that shouldn't be an issue!

I think with your pro and con of hdf5 versus zip is correct: in this case, there are more or less equivalent. Usually, I don't like reading array/table data from a text file, because at one point or another, there is always a formatting, encoding issue, etc. Considering that the main use of the file will be by programs and not many humans will need to read the content of the text file directly - if they need to, they can install HDFview easily or they can use any programming language to read it! In that sense, I think hdf5 is slightly better.

**Comment by gguzzina** [comment]
I think you've really hit the nail on the head. Somehow it hadn't occurred to me that this could be solved by "versioning" the file format itself.

And of course, if we're going to do that, having a decent description of the format somewhere in a repository is essentially a must.

> Regarding how HyperSpy will deal these different GOS (from GMS and this one to start with) and file versions is a different story, but that shouldn't be an issue!

Onestly I think we only need one further GOS class dedicated to opening our new "open" GOS file format in all its versions, and that should be sufficient, since everyone making new work on this will be sure to adopt it ;-)

**Comment by gguzzina** [comment]
I've put together some specification proposal for the file format. It seems reasonable to me, but since we can all be extremely blind to our own silliness, I'd appreciate comments. I attach here a copy of the document in markdown format as well as a PDF export.

[GOS-file specs.md](https://github.com/hyperspy/hyperspy/files/8243528/GOS-file.specs.md)
[GOS-file specs.pdf](https://github.com/hyperspy/hyperspy/files/8243529/GOS-file.specs.pdf)

**Comment by magnunor** [comment]
I had a look at the GOS-file spec, and made a script to generate such a file, and one to read it. See below for these.

---------------

Some comments:

- Should `f['Ti/L23]` be a group, or a dataset? I think maybe having it as group is better, and have the data itself in a `data` dataset, this so that the `variants` can be properly stored. This way, the "axis" information (`free_energy`, `q`) is stored as datasets, not attrs.
- For the `variants`: I don't think this can be saved as a `dict`, so I stored this as a group with the `.keys` and `.values` as datasets.
- Should the dtype of the values be specified? For example in edges_table `n` and `l`
- If there is only one variant, should the edge data be 2- or 3-dimensional? Ergo, for `m x n x 1`, should the dataset by 2- or 3-D?
- I think the `root` of the HDF5 file should contain information about the "file format" and the version of the file format.

----------------

Should the file spec repository also include an example script which generates a spec-compliant GOS HDF5 file? This could also include an example script on how to read it.

Lastly, it could also include a simple file "validator" which returns an error message if something is wrong, and returns nothing if everything is correct. This could essentially be the file reader, but with some `assert` + error messages.


------
## File writer

```python
import numpy as np
import h5py

q = np.arange(0, 10, 0.1)
free_energy = np.arange(500, 600, 0.1)
variants = {0: 'default', 1: '{"relativistic": "low", "oxidation": "3+"}'}
data = np.random.random((len(q), len(free_energy), len(variants)))

#############
f = h5py.File("example_gos_file.hdf5", mode="w")

#############
f.attrs.create('file_format', 'GOS5')
f.attrs.create('file_format_version', 0.1)

#############
metadata_group = f.create_group('metadata')
metadata_group.attrs.create('authors', 'John Doe, Jane Doe')

bib_ref_group = metadata_group.create_group('bib_ref')
bib_ref_group.attrs.create('bib_cite', 'test')
bib_ref_group.attrs.create('bib_doi', '101010101/101010110')
bib_ref_group.attrs.create('bib_url', 'https://')

edges_table_group = metadata_group.create_group('edges_table')
l23_group = edges_table_group.create_group('L23')
l23_group.attrs.create('ref_edge', 'test')
l23_group.attrs.create('normalisation', 1.0)
l23_group.attrs.create('n', 2)
l23_group.attrs.create('l', 1)

#############
group = f.create_group("Ti/L23")
group.create_dataset("data", data=data)
group.create_dataset("free_energy", data=free_energy)
group.create_dataset("q", data=q)
group_variant = group.create_group("variants")
group_variant.create_dataset("index", data=list(variants.keys()))
group_variant.create_dataset("value", data=list(variants.values()))

f.close()
```
----------
## File reader

```python
import h5py

def lists2dict(index_list, value_list):
    output = {}
    for index, value in zip(index_list, value_list):
        output[index] = value
    return output

f = h5py.File("example_gos_file.hdf5", mode="r")

##############
file_format = f.attrs['file_format']
file_format_version = f.attrs['file_format_version']

##############
authors = f['metadata'].attrs['authors']
edges_table_l23 = f['metadata/edges_table/L23']
l23_ref_edge = edges_table_l23.attrs['ref_edge']
l23_normalisation = edges_table_l23.attrs['normalisation']
l23_n = edges_table_l23.attrs['n']
l23_l = edges_table_l23.attrs['l']

##############
ti_l23_data = f["Ti/L23/data"][:]
ti_l23_free_energy = f["Ti/L23/free_energy"][:]
ti_l23_q = f["Ti/L23/q"][:]
ti_l23_variants = lists2dict(f["Ti/L23/variants/index"][:], f["Ti/L23/variants/value"][:])

##############
f.close()
```

**Comment by gguzzina** [comment]
A few further comments.

> * Should `f['Ti/L23]` be a group, or a dataset? I think maybe having it as group is better, and have the data itself in a `data` dataset, this so that the `variants` can be properly stored. This way, the "axis" information (`free_energy`, `q`) is stored as datasets, not attrs.

I don't have any strong feelings either way, and that was the first thing I did. Later if made more sense to me that the axes are a form of metadata over the edge data, and it also produces _slightly_ shorter code. But if you think that's preferable, it's a-ok by me.

> * For the `variants`: I don't think this can be saved as a `dict`, so I stored this as a group with the `.keys` and `.values` as datasets.

A dictionary can absolutely be saved as a JSON-formatted string. Of course this places additional requirements on a file loader, that needs not only to be able to open HDF5 but also parse JSON. That's not a problem in HSPY, but it may be annoying in other languages. Notice that each index of `variants` has a whole dictionary with keys and values, so your file writer does not currently rid us of that problem.

> * Should the dtype of the values be specified? For example in edges_table `n` and `l`

Maybe? In the end even in the specific case it only serves to explain notation. In my mind it's meant more for human eyes than anything else. As quantum numbers they are integers between 1 and 6, but storing them as e.g. float32 does no harm. Upon re-reading it, that part of the proposal strikes me as poorly written, so I tried to improve the language.

> * If there is only one variant, should the edge data be 2- or 3-dimensional? Ergo, for `m x n x 1`, should the dataset by 2- or 3-D?

Either option has pros and cons, and offers different possibilities for mistakes. But I agree it should be specified. Any preference? I'd say stick with 3D because uniformity is nice.

> * I think the `root` of the HDF5 file should contain information about the "file format" and the version of the file format.

In my local copy, I'd added a field in the metadata, but you're right, it's better in the root.

Here an updated version.

[GOS-file specs.md](https://github.com/hyperspy/hyperspy/files/8797152/GOS-file.specs.md)
[GOS-file specs.pdf](https://github.com/hyperspy/hyperspy/files/8797155/GOS-file.specs.pdf)

**Comment by zezhong-zhang** [comment]
Greetings all, 

We (at EMAT, University of Antwerp and Department of Materials, University of Oxford) are also working on GOS development based on Dirac solution, which can be useful for heavy elements due to relativistic effect. Examples of several L edges for transition elements and M edges for Au is as attached. I had a several chats with Giulio and we are pretty agreed that we should have a common standard so that the user can choose freely without bothering of the data structure changes in the code -- hopefully those newly developed GOS can benefit the EELS community for both academic use and industry integration. I am quite happy to take the data structure discussed here and would like to join the discussion : )

I looked of the updated version and have some points for discussion:

1. The `metadata` -> `capabilities` -> `oxidation/quantum numbers` should be specific for each element edge. Thus I am wondering why it keep in the general metadata group instead of have the oxidation, quantum numbers in each element edges group. 
2. For the `ref_edge` in the `edge info`,  we do have the theoretical peak onset value calculated from first-principles (either Hatree-Fock, DFT or Dirac). Also, there are experimentally measured ones, for instance at [EELS.info](eels.info/atlas). Should we distinguish those two values by two attributes?
3. I think maybe it maybe make more physical sense to call 'occupancy ratio' instead of 'normalisation' (though the later is what we do in computation). 
I am interested in how to coherently connect the Zenodo for data hosting and github for example code to download the data & read, but I guess it should be possible as mentioned above.

![image](https://user-images.githubusercontent.com/13212584/175573823-5901e771-f552-4abd-80db-0d7454cea4da.png)
![Au_M45_300](https://user-images.githubusercontent.com/13212584/175577515-fac20caf-8135-4537-84df-7ef1c24cb447.png)

**Comment by gguzzina** [comment]
> The metadata -> capabilities -> oxidation/quantum numbers should be specific for each element edge. Thus I am wondering why it keep in the general metadata group instead of have the oxidation, quantum numbers in each element edges group.

The point of having it in the general metadata group is to signal what physics is modeled by the dataset. That means letting the user know that there are indeed different oxidation states for at least some of the edges. The field should not contain the values of the oxidation state, which should be signaled in the "variants" included with each edge.

> For the ref_edge in the edge info, we do have the theoretical peak onset value calculated from first-principles (either Hatree-Fock, DFT or Dirac). Also, there are experimentally measured ones, for instance at [EELS.info](https://eels.info/atlas). Should we distinguish those two values by two attributes?

As far as I can tell the theoretically calculated values are not accurate enough to be of use for spectral fitting, so I didn't see any use in including them. In fact, I had not even considered including onset values at all. You think we should? I am open to it.

> I think maybe it maybe make more physical sense to call 'occupancy ratio' instead of 'normalisation' (though the later is what we do in computation).

Sure. Works for me.

>  I am interested in how to coherently connect the Zenodo for data hosting and github for example code to download the data & read, but I guess it should be possible as mentioned above.

Honestly it may just be easier to include an example script in Zenodo, alongside the data (which is allowed).

**Comment by gguzzina** [comment]
@ericpre I can quickly create a gitlab repo to host the specification description, but I wonder whether it could make more sense to host it directly somewhere within the hysperspy repository, maybe as part of the documentation.

**Comment by gguzzina** [comment]
I finally published the data.

https://zenodo.org/record/6599071

A paper is in preparation, as is the publication of the relevant source code.
The code for using this inside hyperspy is nearly finished, but I need to add support for a configurable filepath, the documentation, and the tests

**Comment by gguzzina** [comment]
And the source code is published!
https://github.com/Br0Fi/goscalc

**Comment by ericpre** [comment]
Done in #3082 and now in [`exspy`](https://hyperspy.org/exspy/user_guide/eels.html#generalised-oscillator-strengths).
