### ISSUE TITLE
Matplotlib 3.5 support

### ISSUE THREAD

**Issue by jheinen** [hyperspy/hyperspy#2860]
Is there a specific reason, why `hyperspy` is limited to `matplotlib>=3.1.0,<3.5`?

**Comment by ericpre** [comment]
Unfortunately, some of hyperspy widgets are broken with matplotlib 3.5 and this is why it was pinned in [hyperspy 1.6.5](https://github.com/hyperspy/hyperspy/pull/2844#issue-1036546451).
This should be fixed in hyperspy 1.7 soon but there is still some pending PR that we need from the matplotlib side to properly fix the widget issue...

**Comment by ericpre** [comment]
@jheinen, does it answer your question? If so, should it be closed?
