### ISSUE TITLE
Key error loading Bruker .bcf file

### ISSUE THREAD

**Issue by TMoon96** [hyperspy/hyperspy#2881]
![Screen Shot 2022-02-15 at 9 31 34 AM](https://user-images.githubusercontent.com/99740919/154082687-4014dd15-4c6f-4f72-b42d-d564892b8298.png)
![Screen Shot 2022-02-15 at 9 17 07 AM](https://user-images.githubusercontent.com/99740919/154079952-e0bca9d8-cfeb-4e61-8d66-b538b5dc696c.png)
I'm trying to load a EDS map .bcf file using the most basic method (define path name and using hs.load(path), and get the error "Key error: 'Line'." Setting load_original_metadata to false does not resolve this. This file was recorded the same day as two others, one of which gives the same error but the third loads just fine. The files also open just fine in Bruker's ESPIRIT software.

**Comment by hakonanes** [comment]
Hi @TMoon96,

I'm not very familiar with the .bcf IO plugin, but it seems to me like it is too strict, as this try/except block should also except your `KeyError` and move on:

https://github.com/hyperspy/hyperspy/blob/db5743b294703cf0418d72846356c7f54db9ee95/hyperspy/io_plugins/bruker.py#L732-L749

If you change the line to `except (AttributeError, KeyError)`, at least your file reading won't fail on that part. Could you try that locally? If it works as expected, I suggest making a PR with that change, if maintainers agree.

**Comment by TMoon96** [comment]
Thanks, that worked as you described. I'm wondering if I just didn't save the file with elements identified, but since the code should work in either case the change should probably still get made.

**Comment by hakonanes** [comment]
> Thanks, that worked as you described.

Great!

> I'm wondering if I just didn't save the file with elements identified, but since the code should work in either case the change should probably still get made.

I agree, you should be able to read either way. Do you want to make a PR?

**Comment by ericpre** [comment]
It would be good to make a PR to fix it, if bruker software can open the file, it would be fair to expect hyperspy to be able to open it, even if some metadata are missing, even if we don't know why this specific file doesn't have this metadata. There is a tradeoff between letting the code fails to get user to report issue and convenience. In this case, maybe, a warning could be raised when loading the file?

**Comment by hakonanes** [comment]
Raise the log entry to a warning, or in addition?

**Comment by ericpre** [comment]
Catch the error to allow loading the file and raise a warning (using the logger?) to inform the user that some information may be missing.

**Comment by hakonanes** [comment]
Currently, the try/except clause catches an attribute error, presumably raised by `xml.etree.ElementTree.find()` when some tree entry string isn't found, makes a log entry, and moves on.

https://github.com/hyperspy/hyperspy/blob/db5743b294703cf0418d72846356c7f54db9ee95/hyperspy/io_plugins/bruker.py#L748-L749

I think the log message describes the present error nicely, and suggest to just catch the present `KeyError` as well, and raise the log entry to a warning, because the warning will be added to the log anyway...?

**Comment by ericpre** [comment]
Yes, that may be already good enough! If @TMoon96 can understand why it raises a different error using its file than the one that is currently expected, it would be good but this is not necessary. In this case, it would be useful to look at what are the keys of [`tmp_d`](https://github.com/hyperspy/hyperspy/blob/db5743b294703cf0418d72846356c7f54db9ee95/hyperspy/io_plugins/bruker.py#L745)?

**Comment by sem-geologist** [comment]
@TMoon96, could You send the erroring bcf file? I guess that You had selected some elements. In some versions/implementations/adaptations of Esprit, some of XML nodes are not populated. Or at least tell us what elements had You selected. In some cases it could be that element has not much lines to chose from, and Esprit could try omit that information. the PR #2900 tries to skip past the error instead of handling it correctly, as a consequence You will get no list of elements selected in Hyperspy metadata. Proper fix, should still keep the parsed element (abbreviation), catch the missing `Line` and fill it automatically (I think the safest approach is default to `KA` line). I guess it can be so for low atomic number elements, but It would be really good to see the file which made this error.
