### ISSUE TITLE
Forcing s.plot() into a Tkinter canvas

### ISSUE THREAD

**Issue by blanc17** [hyperspy/hyperspy#2973]
Hello, 

I am trying to create a Tkinter program using HyperSpy as a basis to analyze TEM and SEM data.

I love what the output for s.plot(True) is able to look like, but I don't like that calling it (when a backend is enabled) opens a new window.
Is there a way to force s.plot() into a specific frame/canvas? Or (like in the HyperspyUI) for the windows that are created to only popup in the main Tkinter window, and not individually outside of the main?

Thank you for your time

**Comment by ericpre** [comment]
This should be possible but I don't think that there is a public API to do this.

Could you make a plugin to HyperSpyUI to do what you need? Or is this a blocker with using HyperSpyUI? It does need some TLC but it has a good infrastructure.

On a side note, the matplotlib support for the Tk backend is not as comprehensive as for the Qt backend.

**Comment by blanc17** [comment]
Thank you for your response!

I considered going in and attempting to change code in the HyperSpyUI, but I downloaded the HyperSpy bundle and, in all honesty, I am unsure how to change things (without breaking the program) and what would need changed. Is it possible to make a plugin with the bundle for the UI? 

Sadly, I found out the Qt backend was more compatible after developing a semi-working program with Tk. (I apologize - am a bit new to Python and I simply looked up how to code Python GUIs instead of looking at compatibility.)

**Comment by ericpre** [comment]
There is some documentation (https://hyperspy.org/hyperspyUI/devguide.html) and it is better to have some programming experience. If you are new to python but experience with other languages, you should be fine.
You can make your own plugins without breaking the rest.

I don't know how sophisticated is/will be your program, but making a GUI is tedious, time consuming and not easy to maintain!

**Comment by blanc17** [comment]
Perfect thank you! Sadly, I do not think plugins will work for exactly what I had in mind but they might help me in the future.

And you're quite right... making a GUI has been very tedious!

**Comment by jat255** [comment]
I think Eric's response is pretty close to what I would have said. As you found, HyperSpyUI (http://hyperspy.org/hyperspyUI/) does some of this, but using Qt rather than Tk. Ultimately, HyperSpy's plotting code is all matplotlib-based, so there should be a way to coerce it into a frame of your choosing, but that would be a pretty exploratory effort (and I wouldn't really know where to start besides taking a close look at the plotting code).

Depending on your needs, you could perhaps consider modifying/extending the existing HyperSpyUI code? While not heavily used, it is a "full" GUI already built that may remove a lot of the tedium from your project. 

There's also Nion Swift (https://nionswift.readthedocs.io/en/stable/index.html) which is made by a company (Nion), but is fully open source. It doesn't use HyperSpy, but it's written in Python and Qt and might give you another starting point/ideas. I'm a big fan in general of not reproducing efforts and making use of the hard work that others have already done. 

Also, depending on your goals/project requirements, if you wrote something within HyperSpy or HyperSpyUI, it could potentially be contributed upstream and be used by others, and give your work more utility beyond the walls of your institution, which is always nice.

*NIST disclaimer: Any mention of commercial products is for information only; it does not imply recommendation or endorsement by NIST.*

**Comment by blanc17** [comment]
Thank you for the response! I did consider potentially modifying the HyperSpyUI code, but determined that may be a better step after I more thoroughly understand Python and GUI creation. Thanks again.
