### ISSUE TITLE
Scipy conference July 8-14 Tacoma, WA 

### ISSUE THREAD

**Issue by francisco-dlp** [hyperspy/hyperspy#3295]
With the 2.0 Release, HyperSpy is now fully free from its microscopy bias. Therefore, I think that the time a ripe to submit an abstract to the Scipy Conference (deadline 27th of February). Is there anybody interested in presenting a talk on HyperSpy at the Scipy Conference?

**Comment by CSSFrancis** [comment]
@francisco-dlp I think this is a great idea. (Just because I couldn't find the website easily [here](https://www.scipy2024.scipy.org/) is the link.

I probably won't be able to attend (still trying to figure out a job/post graduation plans but I might be able to figure something out before Feb 27th)  

In general we probably need some better advertising and need to start to bring in some more people to work on the project.  Maybe we should talk a bit more about funding/ next steps etc.

**Comment by ericpre** [comment]
Moving to GitHub discussions.
