### ISSUE TITLE
Position of text marker is incorrect when using mathtext

### ISSUE THREAD

**Issue by ericpre** [hyperspy/hyperspy#3315]
As reported by @viljarjf in https://github.com/pyxem/pyxem/issues/1022#issuecomment-1953064882, the position of marker is incorrect when using matplotlib ["mathtext"](https://matplotlib.org/stable/users/explain/text/mathtext.html) (usetext=False).

```python
from hyperspy import api as hs
import numpy as np

data = np.arange(100).reshape((2, 2, 5, 5))
signal = hs.signals.Signal2D(data)

signal.plot()

offset = [[3, 3], ]
raw_text = "$\\bar{1}$"

point_marker = hs.plot.markers.Points(offset)
text_marker = hs.plot.markers.Texts(offset, texts=[raw_text,], color="red")

signal.add_marker([point_marker, text_marker])
```

**Comment by CSSFrancis** [comment]
I think that the problem is here:
https://github.com/hyperspy/hyperspy/blob/325f611a4323ab6e78793d735679a16f2ccd31dc/hyperspy/external/matplotlib/collections.py#L417

We need to have `ismath=True` when there are "$$" in the string.

See the function here:

https://github.com/matplotlib/matplotlib/blob/9e18a343fb58a2978a8e27df03190ed21c61c343/lib/matplotlib/textpath.py#L48-L70

The `usetex` option is nice but requires that you use latex to render which means you have to have latex installed and available to matplotlib.

**Comment by ericpre** [comment]
Done in #3319.
