### ISSUE TITLE
signal types do not exist in hyperspy 2.1.1

### ISSUE THREAD

**Issue by laenglem** [hyperspy/hyperspy#3427]
#### Describe the bug
According to the [documentation](https://hyperspy.org/hyperspy-doc/current/reference/api.signals/BaseSignal.html) the command below should show five different available signal types, however, when executing the command zero options show, also a 1D dataset can not be transformed into EELS data anymore by changing the signal type

It seems like EELS signal type simply does not exist in this hyperspy version, actually, none of them exist

#### To Reproduce
```
hs.print_known_signal_types()

s = hs.signals.Signal1D([0, 1, 2, 3])
s.set_signal_type("EELS")
```

#### Expected behavior
output of the command is only:
signal_type 	aliases 	class name 	package

output of the second command:
Error message with:
WARNING | Hyperspy | `signal_type='EELS'` not understood. See `hs.print_known_signal_types()` for a list of installed signal types or https://github.com/hyperspy/hyperspy-extensions-list for the list of all hyperspy extensions providing signals. (hyperspy.io:744)

#### Python environment:
 - HyperSpy version: 2.1.1
 - Python version: 3.12.5

**Comment by laenglem** [comment]
s = hs.signals.Signal1D([0, 1, 2, 3])

is how the signal was created

**Comment by laenglem** [comment]
Alright, I found out that I have to install the package
exspy
as well, but I feel like this is not properly documented.

I would suggest installing this together with hyperspy

**Comment by ericpre** [comment]
Since hyperspy 2.0, hyperspy is domain agnostic by design. Unfortunately, https://github.com/hyperspy/hyperspy-extensions-list  out of date, because the script that update it automatically fails because an extension doesn't support hyperspy 2.0.

https://hyperspy.org should give you an overview of the eco-system.

The docstring of [`set_signal_type`](https://hyperspy.org/hyperspy-doc/current/reference/api.signals/BaseSignal.html#hyperspy.api.signals.BaseSignal.set_signal_type) mentions that external libraries are required to provide signal type, but it would be good more explicit in the example section of that docstring.

In the hyperspy user guide, we recommend to use hyperspy-bundle as this would include all relevant librairies. In case where users install the libraries by themselves, we expect that they will be aware of what library they need to install.
