### ISSUE TITLE
FYI playing around with pint and pydantic --discussion

### ISSUE THREAD

**Issue by uellue** [hyperspy/hyperspy#3429]
In LiberTEM we have been brainstorming on how metadata can be specified and validated in such a way that it works for both software developers and users. We found it pretty challenging to make metadata consistent even within our own project.

We've [combined `pydantic` and `pint`](https://github.com/LiberTEM/LiberTEM-schema/blob/main/src/libertem_schema/__init__.py) so that a schema can be defined easily:

```python

class Simple4DSTEMParams(BaseModel):
    '''
    Basic calibration parameters of a strongly simplified model
    of a 4D STEM experiment.

    See https://github.com/LiberTEM/Microscope-Calibration
    and https://arxiv.org/abs/2403.08538
    for the technical details.
    '''
    overfocus: Length
    scan_pixel_pitch: Length
    camera_length: Length
    detector_pixel_pitch: Length
    semiconv: Angle
    cy: Pixel
    cx: Pixel
    scan_rotation: Angle
    flip_y: bool
```

...and also instantiated easily:

```python
params = Simple4DSTEMParams(
    overfocus=0.0015 * ureg.meter,
    scan_pixel_pitch=10000 * ureg.angstrom,
    camera_length=0.15 * ureg.meter,
    detector_pixel_pitch=0.000050 * ureg.meter,
    semiconv=0.020 * ureg.radian,
    scan_rotation=330. * ureg.degree,
    flip_y=False,
    cy=(32 - 2) * ureg.pixel,
    cx=(32 - 2) * ureg.pixel,
)
```

Missing parameters or dimensionality mismatch will lead to a validation error when trying to instantiate. See [the tests](https://github.com/LiberTEM/LiberTEM-schema/blob/c096d5337f21c78232134ad9d9af19b8405b1992/tests/test_schemas.py#L1) for more usage and error scenarios. The instance can be serialized as JSON, the schema as JSON Schema, and then both can be also validated with, for example, `jsonschema`. That means it is portable between programming languages and anything that maps from and to JSON.

For the time being we are just trying to make parameters consistent within LiberTEM (next step is starting to actually use it there), but in the future one could think about translating equivalent parameters, or perhaps define the HyperSpy metadata schema like that? I was looking if I could find some schema definition from HyperSpy so that we can re-use it, but it seems to be mostly defined by convention? Please correct me if I am wrong!

Long story short, since this is, in the end, about interoperability, I figured it could be nice to share it and start a discussion!

CC @sk1p @magnunor @matbryan52

**Comment by CSSFrancis** [comment]
@uellue This is a great discussion.  There has been some previous discussion on [metadata](https://github.com/hyperspy/hyperspy/issues/2095) but we have previously run into a bit of a roadblock defining how metadata should be handled.  I think it's important to have a standard but not be too ridged such that you continue give people flexibility.  

There is added complexity when you are trying to be domain agnostic.  The example that always comes to mind of this is how the xray community defines reciporical space in terms of "q" where the electron diffraction community uses "k" both have units of angstroms^-1 but they are off by a factor of 2pi!  Hyperspy does use pint and you can do something like `s.isig["1nm":"2nm"]` to slice using real units.  Although `s.isig[1 *nm : 2 *nm ]` might be more pythonic. 

I've thought of this a bit downstream in pyxem and made a [Calibration](https://github.com/pyxem/pyxem/blob/main/pyxem/utils/calibration.py) class.  Somethings that might be worth thinking of:

- What if your pivot point correction is wrong. Should that be corrected (currently what we do in pyxem) or can an array of centers be passed.
- What happens when you change the scale?  Does the center value also update? 
- Does your reciporical space scale depend on your camera length? It tecnically should be non linear when expressed in inverse nm/angstroms and should be linear when expressed in terms of mrad. That is seldom done in electron microscopy but essential for xray diffraction. 
- How do you express non-linear scales? 
- Could you extend this to something that has arbitrary scan positions? 
- Do you need to make a new class for 5D STEM metadata? What about 6D or ND?

A couple of other thoughts:

1. How hard is it to remove the LiberTEM dependancy? 
2. Can you reliscense MIT or some other permissive liscense.  Direct Electron (and other microscope vendors) would love an open source metadata format to write to.

**Comment by sk1p** [comment]
Just to quickly address these two points:

> 1. How hard is it to remove the LiberTEM dependancy?

For the schema repo, there is none: https://github.com/LiberTEM/LiberTEM-schema/blob/c096d5337f21c78232134ad9d9af19b8405b1992/pyproject.toml#L12-L16

> 2. Can you reliscense MIT or some other permissive liscense.  Direct Electron (and other microscope vendors) would love an open source metadata format to write to.

Already is: https://github.com/LiberTEM/LiberTEM-schema/blob/main/LICENSE :)

**Comment by CSSFrancis** [comment]
@francisco-dlp @jat255 @bbammes @jlaehne
