### ISSUE TITLE
Making the most of auto-completion

### ISSUE THREAD

**Issue by pburdet** [hyperspy/hyperspy#494]
(Original proposal by @pburdet is just below)

This is being implemented in #566, see #566 for an up-to-date progress status and final implementation details.

**Comment by pburdet** [comment]
#1 moving to utils

To make the most of auto completion and to helps user to find/remember the function of hyperspy, I suggest to move a maximum of method under utils.

- preferences -> utils.preferences
- __version__ -> utils.__version__
- get_configuration_directory_path -> utils.get_configuration_directory_path
- model
   - components -> utils.model.components
   - create_model -> utils.model.model
- load -> utils.load (I'm not sure about this one)
- signals -> utils.signals (I'm not sure about this one)

#2 Simplifying utils

Mainly for a nicer looking

- utils.plot.plot_spectra -> utils.plot.spectra
- utils.plot.plot_images -> utils.plot.images
- utils.plot.plot_signals -> utils.plot.signals
- utils.plot.plot_histograms -> utils.plot.histograms

#3 Package other than hyperspy

For the user to be aware when he is using hyperspy and to help him to understand python, I suggest to stop importing the full package. I think it's a best practice and it will help attracting people from the python community

- from numpy import * -> numpy as np
- from matplotlib.pyplot import * -> import matplotlib.pyplot as plt

**Comment by to266** [comment]
Moving things around too much would break a lot! Or we'd have to write many new functions for backwards - compatibility. One way to mitigate it would be to only have "links" in the utils (with some sort of explanation).. However most of the functions are not utils in the technical sense.

Maybe then some sort of `utils.helper`? It could be either links to the actual methods / objects, etc, or just functions printing out documentation of the function/structure, etc. Either way the auto-completion should be used for the helper.

--------------

I'm all for the simplification, I think it makes sense


-----------------

That would make a lot of sense too, especially considering that is the direction the IPython is going forward to and encouraging. However, I would still like to not have to remember to include all the things myself! So either (somehow) adding the include lines at the top when creating a new notebook or (in case of console/QTconsole) just printing what was done would be useful.

On the other hand, then there is less sense in providing the "bundle" - the hyperspy is then used exactly as any other imported package..

**Comment by francisco-dlp** [comment]
I fully agree with @pburdet, we have to undertake a major reorganization of the placement of the public interface. As it seems that we all agree in that we should stop injection all `hspy` into the user namespace, then, most of @pburdet suggestions are already in-place:


* [x] `preferences` -> `hs.preferences`
* [x]  `__version__` -> `utils.__version__`
* [ ] `get_configuration_directory_path` -> `hs.utils.get_configuration_directory_path` 
* [ ] model
   - components -> utils.model.components
   - create_model -> utils.model.model
* [ ] load -> utils.load (I'm not sure about this one)
* [ ] signals -> utils.signals (I'm not sure about this one)
* [ ] utils.plot.plot_spectra -> utils.plot.spectra
* [ ] utils.plot.plot_images -> utils.plot.images
* [ ] utils.plot.plot_signals -> utils.plot.signals
* [ ] utils.plot.plot_histograms -> utils.plot.histograms

I suggest slightly different placements for the ones that are not already as @pburdet  suggests:

* [x] `get_configuration_directory_path` -> `hs.get_configuration_directory_path` 
* [x] model
   - `components` -> `hs.components`
   - `create_model` -> `hs.create_model` (this one will be deprecated in 0.9 anyway)
* [x] `load` -> `hs.load`
* [x] `signals` -> hs.signals 
* [ ] `utils.plot.plot_spectra`-> `hs.plot.plot_spectra`
* [ ] `utils.plot.plot_images` -> `hs.plot.plot_images`
* [ ] `utils.plot.plot_signals `-> `hs.plot.plot_signals`
* [ ] `utils.plot.plot_histograms` -> `hs.plot.plot_histograms`

And so on. So, you can summarise this as: get rid of `utils` and move everything in there to `hspy`.

The only thing in which I disagree with @pburdet is in renaming `plot.plot_spectra` to `plot.spectra` etc, because I think that the name of the functions should be able to stand on their own i.e. without the need to know the name of their module in order to "complete" their name.

It'll be nice to do this for 0.8.1, maintaining compatibility with the previous structure but warning the users that the structure will change for good in 0.9. What do you think?

**Comment by to266** [comment]
I think that should be fine.

The only problem then is backwards-compatibility... Though a manual import of the hspy into the userspace should fix it, we'll just have to warn people everywhere.

**Comment by pburdet** [comment]
That's true. If we encourage the use of ``hs``, then we can get rid of ``utils``. 

To keep things tidy, should we have ``hs.model.components``, ``hs.model.create_model`` and ``hs.io.get_configuration_directory_path``?

Ok for ``plot.plot_spectra``, it is effectively better to keep the function name the same

**Comment by francisco-dlp** [comment]
`hs.model.components` is more telling than `hs.components`, but I would hesitate to create a new submodule (`model`) that just contains another submodule (`components`) (`create_model` will be deprecated in 0.9). What about `hs.model_components`?

The same goes for `hs.io.get_configuration_directory_path`, I think that it is not worth to create a submodule for just one function. We could classify the different function in the `hspy` module docstring instead.

**Comment by vidartf** [comment]
> That's true. If we encourage the use of hs, then we can get rid of utils. 

If we stop injecting all of hspy, then I agree that we could still keep things top-level is hspy. Whereas the old `load` function overrode the builtin one, `hs.load()` is safe and straight forward. We could of course put it as `hs.io.load()`, but I think that's overly verbose. I like `hs.model_components`, as long as there is not too much other things in hspy that start with "model" (it would make autocomplete take extra steps to resolve the name fully).

**Comment by francisco-dlp** [comment]
ok, given that most agree that this is a good thing, let's add it to the 0.8.x milestone. If anybody disagrees, speak before it is too late. I will also update the description to summarise the changes that we have agreed on so far.

**Comment by vidartf** [comment]
Sure, but if we're breaking backwards compatibility, then at least we should strive that we get everything right in one go, so that users only have to update any existing code *once*.

**Comment by francisco-dlp** [comment]
I fully agree, that's why, given that this and #541 has the potential of being highly disruptive for the users, we should really make sure that we all agree on the chages. So please, if anybody has any concern with the changes summarised in the header of this issue or would like to propose some more, this is the time to raise your concerns.

Once we reach agreement, it'll be a good idea to describe the proposed changes in the mailing list so that the users who don't follow this discussion in GitHub can also contribute their opinion.

**Comment by vidartf** [comment]
Just a though: Together with the new API we could include a module called `hspyold` or similar, which users would be able to import/inject to keep old code running. We could then raise a deprecation warning on import, and not directly include any new features in that module to push users to adapt to the new API.

**Comment by francisco-dlp** [comment]
That's an excellent idea. However, I propose to have it only for 0.8.1 and remove it for 0.9.

**Comment by francisco-dlp** [comment]
To help everybody to migrate (and also ourselves to refactor the code and docs) we could provide a tool to convert scripts and notebooks to the new syntax, what do you think?

**Comment by francisco-dlp** [comment]
Should we move `markers` to `plot`?

**Comment by vidartf** [comment]
What would be the difference between `drawing` and the new `plot`?

**Comment by francisco-dlp** [comment]
`drawing` is an internal module (i.e. only for internal consumption, users are not supposed to import it) while the new `plot` (which previously was in `hspy.utils.plot` is part of the API, does this make sense?

By the way, I started working in implementing this yesterday and I thought that (as suggested by @vidartf ) we could keep `hspy` as it is and implement the changes in a new module called `hyperspy.api`, what do you think?

**Comment by vidartf** [comment]
Yes, then I agree markers should go in the new `plot` package, but I'd want to know what @pburdet thinks since he initially wrote that.

Having a subpackage called `api` is very descriptive, and in line with convention of several other packages, so that would be a good change I think. We would still add a deprecation warning to `hspy`?

**Comment by francisco-dlp** [comment]
I suggest the following:

* Ship the new `api` module with `0.8.x` but don't import it automatically when using the `hyperspy` script.
* Provide a new option in preferences to automaticall import from `hyperspy.api` instead of `hyperspy.hspy` when using the `hyperspy` script.
* Raise a warning when importing from `hyperspy.hspy` informing the user that
    - `hyperspy.hspy` is deprecated and will be removed in `0.9`.
    - Importing from `hyperspy.api` when using the `hyperspy` script can be enabled in `preferences`.

Also, it might be good to provide a conversion tool for this and the API changes described in #541.

Does this sound good to everybody?

**Comment by to266** [comment]
I think I agree, just one question:

In the `0.8.x` do you still want to automatically import `hyperspy.hspy`? 
I assume not, as we will most likely release with the newerst ipython versions and try to use https://github.com/hyperspy/hyperspy/pull/564?

**Comment by francisco-dlp** [comment]
I'm afraid that the answer is yes as the transition must be smooth for the users. For example, we could do that by default but raising a warning encouraging the users to set the (new to-be-written) preferences setting `preferences.General.legacy_import_all` to `False`(default to `True`).

**Comment by pburdet** [comment]
`Markers` in `plot` makes sense. I agree also with the rest: `hs.get_configuration_directory_path` and `hs.model_components`. We need to find a right balance between too many nodes and too many object in `hs.`. It would by nice if we get a good pictures of hyperspy functionallity by looking at the list obtain pressing tab after `hs.`

**Comment by to266** [comment]
Hm, I'm not sure if that's possible / easy, but we could try to add some sort of `__repr__` functionality to the `hs` namespace - there printing sort of the "menu" what the hyperspy offers (probably only the first 1-2 layers of it) with descriptions - in a similar manner to the `DictionaryTreeBrowser`.

**Comment by francisco-dlp** [comment]
> we could try to add some sort of __repr__ functionality to the hs namespace - there printing sort of the "menu" what the hyperspy offers (probably only the first 1-2 layers of it) with descriptions - in a similar manner to the DictionaryTreeBrowser.

I'm -100 on this: there is already a standard way to get to know the project's structure: it's docstring e.g.:

```python
In [1]: import hyperspy

In [2]: hyperspy?

```
```
Type:        module
String form: <module 'hyperspy' from '/home/fjd29/Python/hyperspy/hyperspy/__init__.pyc'>
File:        ~/Python/hyperspy/hyperspy/__init__.py
Docstring:
HyperSpy: a multi-dimensional data analysis package for Python
==============================================================

Documentation is available in the docstrings and online at
http://hyperspy.org/hyperspy-doc/current/index.html.

All public packages, functions and classes are in :mod:`~hyperspy.hspy`. All
other packages are for internal consumption.

When starting HyperSpy using the starting script e.g. by typing ``hyperspy`` in
a console, using the context menu entries or using the links in the
``Start Menu``, the :mod:`~hyperspy.hspy` package is imported in the user
namespace. When using HyperSpy as a library, it is reccommended to import
the :mod:`~hyperspy.hspy` package as follows:

    from hyperspy import hspy as hs

The :mod:`~hyperspy.hspy` package contains the following subpackages:

    :mod:`~hyperspy.hspy.signals`
        Specialized Signal instances.

    :mod:`~hyperspy.hspy.utils`
        Functions that operate of Signal instances and other goodies.

    :mod:`~hyperspy.hspy.components`
        Components that can be used to create a model for curve fitting.

More details in the :mod:`~hyperspy.hspy` docstring.

```

Note that in #566 I have tried to improve this docstring.
