### ISSUE TITLE
Use external library for 1D-peakfinding

### ISSUE THREAD

**Issue by magnunor** [hyperspy/hyperspy#711]
Currently HyperSpy uses `spectrum.find_peaks1D_ohaver()` for doing 1D-peakfinding, which is a translation of MatLab code: https://github.com/hyperspy/hyperspy/issues/628#issuecomment-125270246

In my experience the routine works ok for most uses, but there are some bugs like https://github.com/hyperspy/hyperspy/issues/628, and it would be better to use a maintained external peak finding routine, from SciPy or somewhere else.

SciPy has [scipy.signal.find_peaks_cwt](https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.signal.find_peaks_cwt.html), which seems like the best bet. But we'll have to play around with the input parameters to find something which works nicely with our "standard" datasets.

**Comment by francisco-dlp** [comment]
I fully agree, maintaining routines for peak finding is should not be HyperSpy's duty, unless the routine is highly targeted to a given type of signal and has no place (yet) in a more general package.

Probably SciPy's `find_peaks_cwt` is a good general purpose one. However, wouldn't it make sense to fix #496 and the use `Signal.map` to apply `find_peaks_cwt` instead of adding a `find_peaks_cwt` to `Signal1D`? In case that there is a doubt about it, this is a real question i.e. I'm not familiar with `find_peaks_cwt` and there may be an advantage in adding a method to provide the feature.

**Comment by vidartf** [comment]
+1 for adding another routine in parallel. I don't think we should remove
the other unless we find another that works by the same principle/algorithm.

**Comment by dnjohnstone** [comment]
Since this has recently been mentioned again in #630 - For info and discussion... I recently spent a fair amount of time searching for good robust peak finding algorithms primarily for 2D cases but also more generally.

It seems to me that there are surprisingly few really solid peak finders out there in big Python packages with most being ugly multi-step things requiring a lot of manual tuning. Most people seem to have situations where the number of signals/peaks is enough that some automation is helpful but sufficiently few that lots of manual tuning is viable.

I think that the need for really robust and maximally automatic peak finders is inherently linked to having big multi-dimensional datasets and so in that regard does fall within the domain of HyperSpy. Also, what works depends a lot on the particular data so maximum choice also has to be good. In short, I'd be very reluctant to remove this peak finder just so that we don't have to keep a peak finder working.

**Comment by tjof2** [comment]
Further to @dnjohnstone's point, my work is focused on identifying single atoms in noisy STEM datasets, and **robust** 2D peak-finding algorithms are hard to come by generally, let alone in Python. Indeed, one of the "good" ones I suggested to @dnjohnstone doesn't actually work on my data at all...and even state-of-the-art Bayesian methods from the astrophysics community (usually a very good source!) can fail. 

So definitely worth keeping one that "works ok for most uses"!

**Comment by tjof2** [comment]
See #1292 for 2D peak finders

**Comment by tjof2** [comment]
No-one seems to have complained that the current method is insufficient in the last 5 years. It can also be extended using .map as suggested above. Also, 2D peak finding is now also a part of Hyperspy with a number of methods.
