### ISSUE TITLE
Add sound feedback for completed tasks

### ISSUE THREAD

**Issue by Divitini** [hyperspy/hyperspy#719]
Some tasks take an unknown time to compute (for example most decompositions, which can take seconds to hours). Adding a system sound when a long task is completed would save the user the need to go back to keep checking. Could be active only if the task is taking more than, say, 10 seconds in order to avoid being annoying.
Not sure how easy it would be to integrate, but might make the user experience smoother.

**Comment by magnunor** [comment]
I looked a little into this, and implementing this directly into HyperSpy seems to a little complicated due to variations between different operating systems.

However implementing it through IPython seems possible by using the Audio tag: https://stackoverflow.com/questions/17323336/automatically-play-sound-in-ipython-notebook (second answer).

**Comment by francisco-dlp** [comment]
An IPython extension implementing this would very really cool.

2015-09-15 11:22 GMT+01:00 Magnus Nord <notifications@github.com>:

**Comment by vidartf** [comment]
As pointed out in the stackoverflow link that @magnunor posted: If python is running on your local computer (not a server), this should work for all execution methods (quick and dirty):
```python
import os
def pling():
    if os.name == 'nt':
        os.system("echo '\a'")
    else:
        os.system("printf '\a'")
```
Then just call `pling()` at the end of your calculations.

**Comment by jat255** [comment]
There is also this ipython extension that I have used with success. It also
shows a desktop notification from the browser:
https://gist.github.com/robcross/9776646

On Tue, Sep 15, 2015 at 8:49 PM, Vidar Tonaas Fauske <
notifications@github.com> wrote:

> As pointed out in the stackoverflow link that @magnunor
> <https://github.com/magnunor> posted: If python is running on your local
> computer (not a server), this should work for all execution methods (quick
> and dirty):
>
> import osdef pling():
>     if os.name == 'nt':
>         os.system("echo '\a'")
>     else:
>         os.system("printf '\a'")
>
> Then just call pling() at the end of your calculations.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hyperspy/hyperspy/issues/719#issuecomment-140589351>.
>



-- 
Joshua Taillon
Materials Science and Engineering
University of Maryland, College Park
www.joshuataillon.com

**Comment by magnunor** [comment]
@vidartf, I don't think that solution is very reliable, at least for linux systems. In addition using os.system is discouraged due to possible security problems: the subprocess library is the preferred method.

I think having it through ipython is the easiest and most robust way, especially for different operating systems. The people running HyperSpy as scripts directly in the Python interpreter can probably roll their own notification sounds or similar :)

**Comment by tjof2** [comment]
Pretty sure letting users implement this themselves either in jupyter or elsewhere is the way to go, rather than including it in the core package with all the associated maintenance.
