### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by to266** [hyperspy/hyperspy#784]
Just noticed, when running the following code

``` python
In [2]: ax1 = np.arange(-30, 100, 0.01)
In [3]: ax2 = np.arange(-40, 90, 0.01)
In [4]: s1 = hs.signals.EELSSpectrum(np.exp(-np.abs(ax1)))
In [5]: s2 = hs.signals.EELSSpectrum(np.exp(-np.abs(ax2)))
In [6]: s1 = hs.stack([s1]*5)
In [7]: s2 = hs.stack([s2]*5)
In [8]: s1.align_zero_loss_peak(also_align=[s2])
In [9]: s1.spikes_removal_tool()
```

and the clicking the button to plot histogram, there is a memory leak that nearly crashed my system.
Can anyone replicated that, or did I mess something up?

**Comment by francisco-dlp** [comment]
Yes, I have been able to reproduce the bug. The problem is the unusually big signal axis and small navigation size. [This is the loc to blame for this](https://github.com/hyperspy/hyperspy/blob/master/hyperspy/_signals/spectrum.py#L91).

**Comment by francisco-dlp** [comment]
I've looked into this and it seems that the issue is actually in the bin estimator algorithms that we borrowed from astroML `hyperspy/external/astroML`. For some reason it decides that this data requires a huge number of bins and that causes the memory issue. I suggest that we report this issue in the astroML issue tracker and we change the milestone to 0.9.

**Comment by tjof2** [comment]
IMO It's not really a bug @francisco-dlp. There's a few things here:

- The default "freedman" bin width algorithm calculates the bin width correctly. The data has 64995 elements. The smallest value is 3.77e-46, the largest is 0.00995. The IQR is 8.81e-10, giving a bin width of 4.38e-11 - this requires 227094026 bins to cover the range from the smallest to the largest, according to the function definition.
- Numpy >= 1.11.0 (hyperspy currently requires >= 1.10.0) introduced the [`np.histogram_bin_edges()`](https://numpy.org/doc/stable/reference/generated/numpy.histogram_bin_edges.html) function, which means nearly all of the astroML code goes away because you can just call `np.histogram(a, bins="auto", **kwargs)` and it's handled automatically. This approach with the `"auto"` kwarg will *also* return 227094026 bins for the data given above.
- Using "scotts" bin width gives 134 bins which creates no problems.

So, it's really a problem with the specific data provided. There are numerous numpy issues (https://github.com/numpy/numpy/issues/10297, https://github.com/numpy/numpy/issues/11879, https://github.com/numpy/numpy/issues/15569#issuecomment-604095969) and a [SO post](https://stackoverflow.com/questions/60653600/numpy-histogram-extremely-slow-on-small-data-set) on the same subject.

Increasing the min numpy version to 1.11.0 would allow removing nearly all of the astroML code, though preserving the "knuth" and "blocks" bin estimation methods requires some of it to remain. Ubuntu 18.04 LTS numpy version is 1.13.3 so this seems reasonable. cc. @ericpre. 

Here in HyperSpy, the solution could be to calculate the bins using `np.histogram_bin_edges()`, check its not too large (>1000 or something) and avoid the `MemoryError`, until a solution is found upstream in numpy.

**Comment by ericpre** [comment]
xref https://github.com/hyperspy/hyperspy/pull/2272, because it includes small changes in the bin calculations. I don't know how relevant it is for this issue, though...

**Comment by tjof2** [comment]
@ericpre it doesn't change anything, except that if the min version is bumped to 1.11.0, then `calculate_bins_histogram(data)` in #2272 could just be replaced with `np.histogram_bin_edges()`. Indeed that function already has `# Cap at 250 to avoid bad surprised when getting very large number`...
