### ISSUE TITLE
New Signal Classes Proposal & Suggestions

### ISSUE THREAD

**Issue by dnjohnstone** [hyperspy/hyperspy#787]
We've often mentioned the fact that HyperSpy could be used by many people outside of the Electron Microscopy community however at this point there only exists specific Signal classes for EM related signals... In line with discussions regarding steps to encourage new users/developers in #782 I was wondering if we might consider making some new signal classes with basic specific functionality? 

The idea being that (however silly this sounds) making the place to write your functions clear might be one way to reduce the contribution barrier. This issue could also serve as a place for users who might be keeping quiet to suggest signals.

Obvious signals that spring to mind are:
1. RamanSpectrum - most functionality is already there could add a specific correction for the jumps that are seen when slits change over as is common on many spectrometers.
2. PowderXRD - specifically thinking the time series data that people get from in-situ experiments

The list goes on...

**Comment by magnunor** [comment]
Gas chromatography: I've actually written some code for loading datasets, and the modelling part of HyperSpy is very useful since the proprietary software which is bundled with the machines themselves are very limited in what kind of processing you can do. 

I (or my collaborator using it) might actually properly implement it into HyperSpy at some point.

**Comment by CodeMonkeyJan** [comment]
A few people in our institute use HyperSpy to work with holography and phase images (loaded with the plugin added in #741).
I was thinking about adding signals which are subclasses of the Image class and could provide basic functionality like phase wrapping/unwrappig or phase reconstruction from a complex holography image.
As @dnjohnstone mentioned, even having barebone classes would enable people to easily identify where they could add more sophisticated code.

**Comment by dnjohnstone** [comment]
Hi @CodeMonkeyJan yes that would be an ideal case to create a new signal class - I'm also about to pull request an electron diffraction class building on the Image class - are you likely to work on a Holography class yourself?

**Comment by CodeMonkeyJan** [comment]
I have a very crude outline for those two mentioned classes which I wanted to finish after another plugin (hopefully in the next few days). I'll try to encourage my colleagues to fill them with meaningful methods afterwards.

**Comment by dnjohnstone** [comment]
Ok good stuff - just so you know the diffraction thing I mention and my recent push on EDS is largely for work with Martial (who I think you know quite well)....

On a related note that was why I was interested in #710 as I've got some EDS data that I took with you guys that I can't open properly - don't suppose any of you have made any further progress with that? I'm not getting super far.

**Comment by jat255** [comment]
With our new FIB systems, we obtained a TOF-SIMS spectrometer from Tofwerk.
I could picture Hyperspy being used for this sort of data as well. I
believe that the files saved by the software on the SIMS are already some
sort of hdf5 file. As I do not use the SIMS system regularly, I don't have
a lot of motivation to write an import plug in for it yet, but this could
be another class of signal that is of use.

**Comment by CodeMonkeyJan** [comment]
Ah, I see, he is in fact one of the two colleagues I want to convince to contribute here :-).
Furthermore, the plugin I mentioned should be able to read and write EMD files, but those are not the ones from FEI but from Lawrence Berkeley National Lab (see http://emdatasets.lbl.gov/).
As far as I understand, the FEI EMD format came later and is a lot more complicated (with unneccessary nodes all over the place). If at a later stage both EMD formats should be supported this naming conflict could be problematic.
I sadly don't know how far Martial got with reading the data (and he's not here until next year I think).

**Comment by tjof2** [comment]
@CodeMonkeyJan I think holography may well be of use to me!

**Comment by CodeMonkeyJan** [comment]
It's been a while, but we finally had a lenghty discussion about the addition of signal subclasses for electron holography in our work group, but I still have a few questions, before we continue working on that:
- We were thinking about adding two new subclasses, the first being a HolographyImage subclass (directly inheriting from Image and holding 2D real data), whose main purpose will be the reconstruction of a complex wave image from a hologram. The idea was, that the class implements a function which then generates and returns another subclass ("WaveImage", which holds the reconstructed complex image). Is this behaviour (one class having functions, which return instances of another class) desirable? I understand that it would be a different to e.g. the "to_spectrum"-function of the Image class, which works in place without generating a new signal.
- The WaveImage class will host most of the functions which are relevant for holograhpy analysis. It will also inherit from the Image class but it holds complex 2D data. Do we have to expect conflicts in some inherited functions, or do they all work fine with complex data?
- There are other functions (like certain filters, padding, etc.), which could also be beneficial for other types of images, thus the Image class itself may be the best place to put them. Is this in accordance with the current design philosophy (Image itself seems quite empty at the moment)? Or do they even belong in some Signal base class (e.g. Signal2DTools)? I have to admit that I haven't understood the signal structure completely...
- The whole thing will be a combined effort from a few people from our group. From an efficiency standpoint, it would be best to collect our functions in one fork (e.g. my HyperSpy fork). The problem is that I do not want to take credit for stuff that some of my colleague write. I'm still not used to all the intricacies that GitHub offers, maybe someone else has some experience how to handle this? If I merge commits of several users in my branch and then send a pull request to HyperSpy main, will the list of authors include all original contributers?

Thanks a lot :-)

(I'll be on vacation for a few days, but I will be able to respond on Tuesday)

**Comment by magnunor** [comment]
@CodeMonkeyJan, some input to your questions/points:

**New subclasses:**
I think that sounds like a good implementation, and a class with a function which returns a different class as output is pretty common in HyperSpy so that should be ok. For example, `model.as_signal()` or
```Python
s = hs.signals.Image(np.arange(100000).reshape(10,100,100))
<Image, title: , dimensions: (10|100, 100)> # Image class
s1 = s.sum(-1)
<Spectrum, title: , dimensions: (10|100)>
```

**Complex 2D data**
I think this should work, since HyperSpy uses Numpy for all(?) data storage. And Numpy has very good support for complex numbers. I'm guessing some of the functions would need some tweaking, like `s.plot` but that should be pretty easy to change. Like, if the data is complex show one plot window with real values, and one with imaginary values.

**"Upstreaming" functions**
Putting those kind of general functions into more general class would be very nice, and exactly where they should end up would have to be discussed. But I don't think it is that important to figure out straight away exactly which "upstream" class the functions should be in, because it should be trivial to move a function up in the class-chain. So it could firstly be developed in a class inheriting the `Image` class, for example `HolographyImage`. Then, whenever the function is complete, it could be moved into the `Image` class, if it would be useful for other classes which inherit the `Image` class.

And more generally, I think this is one way the HyperSpy project could handle the growing number of things people want to use HyperSpy for: people develop an "extension" to HyperSpy, which inherits the base classes available in HyperSpy. If there are functions (or classes) which would be useful for other use cases, it could be pulled into the HyperSpy base.

**Credit to authors**
This is pretty easy in git, since commits includes information about the author. So if everyone is happy to use git, it should be fairly straight forward. If some people don't want to commit stuff directly through git, you can get the code and commit it in their name: `git commit --author="Name <email>" -m "a commit"`.

**Comment by francisco-dlp** [comment]
@CodeMonkeyJan, it's great news that your plan to integrate your functions for holography is moving forward. I only have a couple of comments to add to what @magnunor posted above.

Some few image functions won't work properly of complex data e.g. `align2D`. Maybe it'll be worth to create a `ComplexImage` class, but we can discuss this in detail once you start pull requesting your classes.

I don't think that it is a good idea to ask you colleagues to send pull requests to your HyperSpy fork. HyperSpy operates like a journal in the sense that every PR is peer-reviewed. Reviewing other people's code is often not an easy task, and it gets daunting when the pull requests contain massive amounts of code. Therefore, we encourage contributors to break things down into small pull requests and to submit the pull requests in the early stages of development to encourage discussion on the details of the implementation. Unless I am misunderstanding you, what you are proposing may lead to the submission of a single huge PR to the main hyperspy repository once you have finished implementing the features in your fork. It'll be very hard for anybody to find the motivation to review a big PR like that. Also, normally the main author of a feature is the one who submits the pull request. The HyperSpy documentation contains links to the PRs to the main HyperSpy repository, which provides an easier way of knowing who's done what than inspecting the individual commits. Therefore, if your colleagues submit PRs to your own fork, although the commits will be credited to their name, it'll be harder to know who's done what in this case. Does it sound reasonable? Don't hesitate to discuss here or in a new issue any doubt that you may have regarding how to contribute to HyperSpy.

**Comment by CodeMonkeyJan** [comment]
Thanks for all the input!
The way I would suggest we go about the implementation of holography features would be the following:

- I will create the barebone structure for two classes which both inherit from the Image class, namely HolographyImage and WaveImage and fitting test modules and send a first pull request.
- Both classes will be empty at first, so that my colleagues can send pull requests in which they can implement their specific functions. For all of them who are reading this, I will of course provide help directly and via the GitHub discussion ;-). This way the pull requests are small and manageble and credit is to whom credit is due.
- If problems with the complex data format of the WaveImage arise, a new intermediate class ComplexImage can be implemented which overrides the problematic functions.
- If functions seem to have a broader range of applications than first imagined, we can think about upstreaming them.

Again thanks for all the input, let me know if this course of action seems okay to you.
