### ISSUE TITLE
saving / loading signals with misleading metadata

### ISSUE THREAD

**Issue by to266** [hyperspy/hyperspy#861]
As shown by https://github.com/hyperspy/hyperspy/issues/859, currently hyperspy fails when loading signals with misleading metadata, leading to people not being able to access the files at all.

In particular, there a spectrum had `metadata.Signal.record_by = "image"`, hence when loading it tried to reshape / rearrange the array and crashed.

We can solve this either when saving (by preventing saving the misleading metadata) or when loading (by failing gracefully and loading the signal as a generic `Signal`, and not the specified subclass).

I'm for the loading solution myself. Thoughts?

**Comment by vidartf** [comment]
We should definitely do the loading solution (with a warning), as this solution allows loading of signals saved with bad metadata before the fix, as well as files with ad metadata created by other sources.

The saving solution could also be implemented, so that our files are more likely to be loadable in other readers and older versions of hyperspy.

**Comment by ericpre** [comment]
`record_by` has been removed from metadata and the signal class assignment mechanism has changed since then.
