### ISSUE TITLE
Website update

### ISSUE THREAD

**Issue by to266** [hyperspy/hyperspy#923]
I am neither experienced nor do I have particularly good ideas, but it's obvious for me that more eye-catching website with more pictures would benefit the exposure. Maybe a video, exhibiting what you can do with the data / how simple it is to use HyperSpy?

Obviously, ideas are welcome.. Volunteers - even more so!

**Comment by magnunor** [comment]
One idea could be having a "gallery", like matplotlib: http://matplotlib.org/gallery.html . I find this gallery to be really useful, since it links to the code which actually generate those images as well.

I'm guessing we already have an example folder, but I don't think it is so heavily used currently.

For example, with some fine structure EELS data it could show a model with all the components added.

**Comment by to266** [comment]
I agree hat the examples should be displayed better, but a gallery of images would be difficult, since not every example is simple to plot / visualize in a single frame. Maybe just extracted snippets? These can even be the same as examples in docs, just compiled in one convenient page with links?

Like a mix of the matplotlib gallery and [this](https://docs.scipy.org/doc/scipy/reference/index.html)

**Comment by francisco-dlp** [comment]
I'm +1000 on any thing that can help enhancing the coolness of the website. Our current webpage looks quite old-fashioned and boring to modern audiences. It does have too much meaningless text and too few catchy figures. Also it is not mobile friendly.

**Comment by tjof2** [comment]
Perhaps a "gallery" of Important results (e.g. selected publications) obtained with HyperSpy, rather than just the doc examples? 

http://hyperspy.org/hyperspy-doc/current/user_guide/bibliography.html#peer-review-articles-with-results-obtained-using-hyperspy was a tricky thing to find...

Perhaps [Jekyll](http://jekyllrb.com) might be a useful way to go w.r.t mobile-friendly themes.

**Comment by jat255** [comment]
I have little to add in terms of actual contribution (since I know little about web design), but I found this site, which might provide some inspiration based off of what some other open source projects have done for their websites: http://beautifulopen.com/

I wonder if the examples section could use some hosted notebooks that show some of the functionality (in addition to static image examples)?

Paging @ewels, who might be able to give us some tips, given his experience with the EELS database.

**Comment by vidartf** [comment]
If static images are unable to convey HyperSpy well, then animated GIFs might be very helpful, c.f. the page for the proposed progress bar library: https://github.com/tqdm/tqdm.

**Comment by to266** [comment]
Yeah, I'm for gifs, however is there a simple / straightforward way to create them? Or just ffmpeg > make a gif?

**Comment by vidartf** [comment]
I'm guessing screen capture is the most straight forward one. I know @jat255 as used gifs for some of his issue reports.

**Comment by jat255** [comment]
Yeah, how did I do that? Haha, I can't seem to remember....

I think I used [LICEcap](http://www.cockos.com/licecap/), which can record direct to GIF. I probably did those screencasts on my Windows workstation, but I think it can run okay in Wine, if necessary. There are also a number of possibilities in [this](http://askubuntu.com/questions/107726/how-to-create-animated-gif-images-of-a-screencast) SE question.

**Comment by ewels** [comment]
Some tips from a part-time web dev:

* Before you touch a keyboard, figure out what the most common reasons for going to the HyperSpy website are, who the audience is and what the top selling points are. Bullet point these, sketch a few homepage variations.
* Start with a HTML / CSS framework such as [Bootstrap](http://getbootstrap.com/) or [Foundation](http://foundation.zurb.com/). Yup, it will make the site look a bit like every other site out there, but will save you a tonne of time and give you stuff like Mobile-responsive pages for free.
* If you don't have anyone very familiar with web dev, use a free template. A bit of googling (`free boostrap templates`) will find you a million and one, then you can start there and modify.
* Strip the text back to the bare essentials and use lots of hierarchy / headings where possible. Use icons where possible (eg. [bootstrap glyphicons](http://getbootstrap.com/components/#glyphicons) or [Entypo](http://www.entypo.com/) or others.

If you want to get really carried away, you can make something like [this](http://clusterflow.io/demo/) - a demo I made for one of my tools which runs entirely in the web browser (and has a bunch of easter eggs built in). JavaScript code [here](https://github.com/ewels/clusterflow-website/blob/master/demo/demo_js.js) to see what you're getting yourself into. Probably my favourite tool website is my [MultiQC website](http://multiqc.info/).

**Comment by tjof2** [comment]
See #1449
