### ISSUE TITLE
Link dev guide in docs

### ISSUE THREAD

**Issue by vidartf** [hyperspy/hyperspy#932]
The [developer guide](http://hyperspy.readthedocs.org/en/latest/dev_guide.html#write-tests-documentation) ( #794, #782 ) is currently not linked from anywhere. It should be included on the front page and in the side bar on the same tree level as the user guide

**Comment by dnjohnstone** [comment]
Ah yes - this will be because I actually have no idea how the website works, so I just put the dev-guide in a folder that looked about right and hoped something magical would happen.

Would be happy to do this if someone points me in the right direction - on the other hand if someone does it, I'll be glad to have learnt something!

**Comment by vidartf** [comment]
See #908 / #909.

**Comment by dnjohnstone** [comment]
This can be closed.
