### ISSUE TITLE
Incorporating Robust PCA into HyperSpy

### ISSUE THREAD

**Issue by tjof2** [hyperspy/hyperspy#972]
A lot of my recent work has focused on robust matrix recovery and completion methods, in particular [Robust PCA](http://perception.csl.illinois.edu/matrix-rank/introduction.html), which is robust to outliers and sparse corruptions, and can also be used for things like spike removal. The method is similar to PCA basically in name only; they're both matrix factorization methods, but RPCA returns a low-rank component **L** (i.e. a model) + sparse error component **S**, rather than the usual scores+loadings seen in PCA. It's good as a denoising step, for inpainting, and also for pre-processing prior to ICA/NMF etc.

I've written a Python implementation of Robust PCA. However, RPCA takes a regularization parameter as the option, rather than an integer number of components to include, and as mentioned returns a model only. As such, I'm not sure how it will fit into the current form of `mva.py` in HyperSpy.

As @dnjohnstone has alluded to elsewhere, PCA, RPCA and others really come under an umbrella of "matrix factorization" methods.

---

As an aside, I've also half-written a version of _online RPCA_, which is much less memory-intensive  (@to266 might be interested in this), and again does not return _U_, _S_, _V_ in the same way as PCA. This could be implemented once we've sorted out this problem.

**Comment by dnjohnstone** [comment]
Just to add in some details from conversations I've had with various people in person.... I think this largely comes down to questions about the overall structure of the "machine learning" part of the code.

I can't see a natural place for a function that returns a learnt model rather than a loading/factor combination. The BSS part of the code is also known to be a bit of a mess.... I know that many of us are stretching ourselves a fair bit at the moment - but 1.0.0 sounds like a sensible place for structural change if the path is clear @francisco-dlp

**Comment by francisco-dlp** [comment]
@tjof2, I think that Robust PCA would indeed be highly interested for many HyperSpy, so we would love to include it in HyperSpy. However, I would suggest that you approach the scikit learn community first to see if they're interested on it as it really belongs there. Once it ships with sklearn, it'll be straightforward to include it in HyperSpy too. If the sklearn community is not interested in RPCA, we can consider then what's the best way to include it in HyperSpy. Does it sound like a good plan?

**Comment by tjof2** [comment]
@francisco-dlp Thanks - there's an [ongoing discussion](https://github.com/scikit-learn/scikit-learn/issues/5851) at scikit-learn about it. I'll look into that.

Separately, as @dnjohnstone mentions, it does raise an important question about the structure of machine learning in HyperSpy that would be worth discussing.

**Comment by tjof2** [comment]
Interestingly, they seem to be having a similar discussion about whether you want the low-rank bit or the sparse bit or both.

**Comment by francisco-dlp** [comment]
The machine learning code is probably the chunk of HyperSpy code that has changed the less since we came out with it and, yes, that structure starts to be limiting for some applications. Changing this structure has been in our radar for some years now. In a way, I am happy that we didn't attempt to tackle this yet, because I think that it is important to get the out of memory features right first. @to266 has been working on that, and `1.0` will ship with support for OOM for many operations, so the time is ripe to tackle this.

**Comment by tjof2** [comment]
This is being addressed in scikit-learn: https://github.com/scikit-learn/scikit-learn/pull/6806, although using the naive implementation of Candes which is about the slowest of the lot.

**Comment by amueller** [comment]
@tjof2 which algorithm would you recommend?
